### ISSUE TITLE
Finish the installation wizard

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#101]
we need to add the instructions from the readme's of all three installation methods ([one](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-jspm-git), [two](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-core), [three](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors))

**Comment by adriatic** [comment]
This means that your plan for the installation wizard to be advisory - not to take same actions based on the results of the interview, right?

I am not proposing to make this similar to a "real installer" but rather trying to understand your plans.

**Comment by JeroenVinke** [comment]
Correct. We will advise what installation method to use (core, vendors or
jspm-git)  and show some easy to follow steps, which depends on the input
of the user
Op 29 nov. 2015 20:41 schreef "Nikolaj Ivancic" <notifications@github.com>:

**Comment by adriatic** [comment]
Perfect - this clearly puts the installation wizard "behind" the other menu items in the sense of priority of user's viewing the demo application and we should make the **about** page be the default.

**Comment by adriatic** [comment]
> We will advise what installation method to use (core, vendors or
jspm-git)  and show some easy to follow steps

This same information (although not in the form of a wizard) should be added to **[this README](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/README.md)** file

**Comment by adriatic** [comment]
Just saw the new wizard and have one suggestion - show the final set of instructions on the same (wizard) page, rather than switching to a new page - so that there cannot be any confusion about what are the choices user has made (the responses to the wizard play the role of "bread crumbs"

**Comment by JeroenVinke** [comment]
I have doubts about the installation wizard, its not worth the complexity. We are better off just creating an html file with instructions per installation method, and have one page where a user can decide which method to use

**Comment by adriatic** [comment]
I have doubts as well as the complexity of the decision making process might not warrant a three page wizard. Graphically, it "unbalanced" as it occupies only a small part of the page

> We are better off just creating an html file with instructions per installation method, and have one page where a user can decide which method to use

I agree
