### ISSUE TITLE
Create the about page for kendo-demo website

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#102]
In order to simplify the process of copying files from aurelia-kendoui-plugin to demo-kendo website, the `about` page should be present  in aurelia-kendoui-plugin "embedded" sample app.

This `about` page should be the the default (landing) page.

**Comment by JeroenVinke** [comment]
@adriatic this has been completed right?

**Comment by adriatic** [comment]
Yes, I am closing this issue
