### ISSUE TITLE
Consider Bind

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia-ui-toolkits/aurelia-kendoui-plugin#103]
Just jumped in here for a few seconds to check things out. You may want to consider using the `bind` callback a bit more on your components, rather than the `attached` callback. For example, see here: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/button/button.js#L25  Could this logic be moved out of `attached` and into `bind`?

Basically, bind happens before the component is attached to the real DOM, but you do have access to your own HTML Element and all properties on your component have their bound values. So, unless the Kendo component is relying on being in the document, you may be able to optimize in this way. It may vary depending on the Kendo widget. I don't know Kendo at all, but I wanted to drop a note here so that you all investigate this option because, if it works, it will result in better performance and user experience.

**Comment by adriatic** [comment]
Thanks for the optimization hint - knowing your workload this is very appreciated and will be used :-)

**Comment by EisenbergEffect** [comment]
No guarantees that it will work with Kendo, but I would try it out for each widget and see. Even if it only works for some, it will improve those implementations.

**Comment by adriatic** [comment]
You mean to move this code from `attached` into the constructor, right?

**Comment by JeroenVinke** [comment]
@adriatic [this line](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/button/button.js#L25) could possibly work inside the `bind` callback, instead of the `attached` callback in which it is now

**Comment by adriatic** [comment]
Oh, well - I am showing my poor Aurelia vocabulary as I never knew that `bind` is a callback (I saw it only in the context of declarative code in HTML)

**Comment by JeroenVinke** [comment]
@adriatic I have just tested this with the sample app inside the plugin, and it works just fine for the controls we currently have. I have also updated the documentation in the wiki's
