### ISSUE TITLE
(Must be a) simple css issue

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#107]
Trying to stuff the current about page into a tab page the content becomes "too wide". Can someone tell me how to tame this css (it ought to be something about "width: xx%" as I recall

![image](https://cloud.githubusercontent.com/assets/2712405/11521929/b158af38-987f-11e5-8813-501f11535b17.png)

Now add a **tab control** so that I can have two about pages - first that tells what is KendoUI "bridge" and the second one that says how to use it (from a very high view - not the Installer wizard level.

I took this simple approach:

![image](https://cloud.githubusercontent.com/assets/2712405/11522027/b471c910-9880-11e5-877d-c1b89760db4a.png)

where a row is defined as 

```html
                <div class="row">
                    <div class="col-xs-12 col-sm-4">
                        <img src="src/images/aurelia-logo-04.png" >     
                    </div>
                   <div class="col-xs-12 col-sm-4">
                        <img src="src/images/bridge-image-08-low.png" >     
                    </div>            
                    <div class="col-xs-12 col-sm-4">
                        <img src="src/images/kendo-logo-05.png" >     
                    </div>            
                </div>
```
It seems that the Bootstrap `<div class="col-xs-12 col-sm-4">` is not happy inside the tab-page as once I do the above the three columns do not fit on a page any more as seen here 

![image](https://cloud.githubusercontent.com/assets/2712405/11522087/6d17b0e2-9881-11e5-92af-5977ad1cd171.png)

**Comment by JeroenVinke** [comment]
This is actually a kendo/bootstrap problem [link](http://stackoverflow.com/questions/20979648/tabstrip-containing-bootstrap-columns). I liked [this answer](http://stackoverflow.com/a/21390066/3922366) so I tried it out, and it works. I have pushed the changes I made into the `css` branch, so you can see exactly [what i've changed](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/compare/css)

**Comment by adriatic** [comment]
Great diagnostic and selection of the remedy - but not so great proof of that fix, since the only change needed is to add 
```
.k-content > .row > *,
.k-content > .row > *::before,
.k-content > .row > *::after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

to file **[styles.css](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/styles.css)**

**Comment by adriatic** [comment]
This change appears in the **css branch** you created as

```
.k-widget > .k-content > *,
.k-widget > .k-content > *::before,
.k-widget > .k-content > *::after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

which of course does no good :-)
