### ISSUE TITLE
Need help with Tabstrip 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#108]
I tried to add the code to Tabstrip **[tab-position.js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/tabstrip/tab-position.js)** file that would cause the same effect as this **[script section](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/tabstrip/tab-position.html#L140-L157)** does for the **[original Telerik demo](http://demos.telerik.com/kendo-ui/tabstrip/tab-position)** set the position of tabs to LEFT, RIGHT and BOTTOM

While I understand how this works in Telerik's world - it seems that I do not understand how it should work in our plugin. While the action of setting the tabs position ought to take place in the JS file, I do not know how to get the access to the three instances of the Tabstrip object that is declared in the **[Tabstrip html](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/tabstrip/tab-position.js)** file.

**Comment by adriatic** [comment]
In analogy with the code for **[button api](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/button/api.js)** sample I tried something like 

```
export class TabPosition {

    this.tabPosition = "left"
}
```

This is clearly not what I want (access the Tabstrip object from JS and set its `tabPosition` bindable to have the value "left")

What is the right syntax I should have used?

**Comment by JeroenVinke** [comment]
I think you need to bind to the tabPosition property. 

```
aurelia-kendoui-tabstrip="tab-position.bind=tabPosition"
```

There are two ways we can handle changes to bindable properties in our wrappers. Firstly we can use the api provided by kendo such as `$(button).enable(true)` in the `enabledChanged` function of our wrapper.  This is the preferred approach.  But kendo hasn't made these api  functions for every possible property of their controls,  which means that for some property changes we observe, we have to destroy and reinitialize the control. This is a more inperformant way than using the api provided by kendo. 

I just noticed that in the sample of the button,  we don't bind to the enabled property, so it doesn't even use the enableChanged function

**Comment by JeroenVinke** [comment]
Also, I don't want to be demotivating, but the tabstrip is also a non-input type control, which means it should be wrapped in a custom element? I will try and get a sample of this working asap

**Comment by adriatic** [comment]
@JeroenVinke writes
> the tabstrip is also a non-input type control

That is so notoriously obvious that I cannot grasp how did I miss that :-)
