### ISSUE TITLE
Get very solid understanding of templating

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#110]
Learn everything about [Kendo templating](http://docs.telerik.com/kendo-ui/framework/templates/overview)

Learn everything about [Aurelia templating](https://github.com/aurelia/templating)

Learn how to "combine" them.

**Comment by JeroenVinke** [comment]
I believe the current [grid wrapper](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js) is incomplete, and some code should be moved from the [gist](https://gist.github.com/charlespockert/1ef96e44f3f15ab60f5e)

**Comment by JeroenVinke** [comment]
The issue is quite old and its not specific enough to pick up. We will learn more about templating when we look into performance improvements of the grid

**Comment by adriatic** [comment]
Good call
