### ISSUE TITLE
recreate control if Kendo API not available

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#111]
if you run the sample of the `recreate` branch, you can see that when you click on the 'change icon button' (see image below), that it should change the icon of the first button, but this doesn't happen. There is also no API from kendo (like `$(button).icon("newIcon")`) to let kendo update the icon.
![image](https://cloud.githubusercontent.com/assets/2189477/11555563/6ce0b7e2-99a1-11e5-87de-86f278eb0b9b.png)

**Comment by adriatic** [comment]
I agree that KendoUI does not provide API to change button image (see http://demos.telerik.com/kendo-ui/button/images as their own demo buttons with images). I believe that Charles did not follow exactly the Kendo's original demo, but did just this

![image](https://cloud.githubusercontent.com/assets/2712405/11608205/77805f46-9b30-11e5-9649-4c987d019b71.png)

So, no need for change button (and if there was one, it should be on the "API" tab, not "Images" tab)

**Comment by JeroenVinke** [comment]
The "change icon" button is just for demonstrating the issue. When you click this button, our wrapper should "see" that the icon property of the first button has changed, and it should re-initialize the kendo button with the new icon, but it does not do this.

**Comment by adriatic** [comment]
So, you are saying that this issue is a bug against [Aurelia Component](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js)?

**Comment by JeroenVinke** [comment]
Yes, if we allow you to bind to a icon property, then we should also let kendo know when the icon changes. since this can't be done with an API, we have to recreate the control perhaps

**Comment by adriatic** [comment]
That I agree with - as it would be bad to hide behind incomplete Kendo API when questioned by Aurelia developers. However, that might be an expensive price to pay  as I am not sure what all controls would have such deficiencies. Kendo folks probably decided that if someone wants to change the icon, let him recreate the whole button - as this could be a reasonable way to address such issue

**Comment by JeroenVinke** [comment]
You have made a good point, but I think this could be very confusing for developers using our wrappers. We need to find out if other controls have the same problem, so we can figure whether or not it's important to fix this.

After we know how we're going to deal with the templating stuff, we can look into this a bit more. But i'd like to do this before our first release

**Comment by adriatic** [comment]
> We need to find out if other controls have the same problem, so we can figure whether or not it's important to fix this.

Yes, that is the proper response :-) - it is the exact opposite of what @jedd-ahyoung advertised (while he was still around): let's just go do something rather than "looking around". 

**Leaving this issue open as a reminder**

**Comment by JeroenVinke** [comment]
Mail conversation with Telerik:

>Hello Petyo,
We are now wondering why there is no 'API' method to change the 'icon' property on a button. The button has an "enable" function, but nothing to change the icon. Is this a design decision, or has it just not been implemented yet?
We see these "missing" API methods in many controls, and for many properties. If we understand why this is the way it is, then we can decide on whether or not to fix this in our wrappers.
Thanks,
Jeroen Vinke.

Response:
>Hi Jeroen,
this is more or less a heritage from the 2011 jQuery plugin era, which we get a lot of flak for :(. 
Most widget configuration options can be set only initially, and can't be changed afterwards. Back then, the rendering mechanism of the widget was not very sophisticated; We also had to support progressive enhancement, which has gone out of fashion since then. 
We work around this in our angular wrappers, using "rebinding" (read - destroy and recreate) of the widget when an option is changed. I would not recommend that, though.  


I propose the following: do not recreate the entire control when a single property changes, but allow the user to call a function on our wrapper to trigger it to recreate.

**Comment by adriatic** [comment]
> I propose the following: do not recreate the entire control when a single property changes, but allow the user to call a function on our wrapper to trigger it to recreate.

This is a very reasonable proposal.

**Comment by JeroenVinke** [comment]
I may have said this before, but I also want to expose the Kendo widget, so users can talk to it directly if necessary.

If we implement an `enable` function in the `button` wrapper, which would just call `enable` on the Kendo control, then the user could do this:

```
// my-page.html
<button au-kendo-button="enable.bind: enabled" au-kendo-button.ref="button">Click me</button>

// my-page.js
somethingHappened() {
  button.enable(true);
}
```

If we somehow forget to implement this function, then users could do this still do this via a `widget` property:

```
// my-page.html
<button au-kendo-button="enable.bind: enabled" au-kendo-button.ref="button">Click me</button>

// my-page.js
somethingHappened() {
  button.widget.enable(true);
}
```



Notice that `button.enable(true);` has changed to `button.widget.enable(true);`. We should have both options available, a function proxy inside our wrappers, and have a `widget` property on our wrappers that contains the actual Kendo control.

**Comment by adriatic** [comment]
You **continue** to amaze me with the depth of your thinking - even in the midst of the excitement that we are so close to show this puppy to the world.

Don't let me spoil your focus with my signs of appreciation, though :+1: So, while I do not remember ever discussing this, please implement it by all means.

**Comment by JeroenVinke** [comment]
Recreating the control is now possible through the `recreate` function, and the instead of the `_component` property we had, it is now `widget`

**Comment by adriatic** [comment]
I knew that you will soon overrun me in my plans to document what we have !!
