### ISSUE TITLE
Gradual buildup of Grid Control

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#112]
This issue addresses the task of creating the Aurelia wrappers for KendoUI grid control. We established that the major problem is that both Kendo and Aurelia have their own templating and we need to find the solution how to make them collaborate in a most efficient way.

In order to really understand this whole situation, I decided to start analyzing things at a much lower level than **[this article](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Kendo-templating-versus-Aurelia-templating:-Problem-definition)**, so consider this (Gradual buildup of Grid Control) article a predecessor.

So, I wanted to start with **[Templating in the context of aurelia kendoui plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Templating-in-the-context-of-aurelia-kendoui-plugin)** and immediately discovered that I need to describe even the more basic setup - **[KendoUI Grid walthrough](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/KendoUI-Grid-walthrough)** where I am showing how to create the "models of grids" in KendoUI native context, without any references to Aurelia. 

Check the following sections and note that this article will grow to cover all our needs for creating the KendoUI Grid wrapper.

Also note that all samples in **[KendoUI Grid walthrough](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/KendoUI-Grid-walthrough)** are instrumented with support to run them in plunker.

- **[Grid Creation](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/KendoUI-Grid-walthrough#grid-creation)**
- **[Our Basic Grid sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/KendoUI-Grid-walthrough#our-basic-grid-sample)**

**Comment by adriatic** [comment]
### Current status on 12/05/2019

The **[Basic Use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/templating/sample/src/grid/basic-use.html)** case of the Grid demo is augmented to show the **[Our Basic Grid sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/KendoUI-Grid-walthrough#our-basic-grid-sample)** introduced **[above](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/112#issue-120606733)**. However, the setup I managed to create is defective as the data shown in the grid

![image](https://cloud.githubusercontent.com/assets/2712405/11611668/6e1f4b16-9ba7-11e5-9831-b42cefd0cc3c.png)

contains a lot of "garbage" meaning that the view
```html
 <au-kendo-grid data-source.bind="datasource" auto-bind.bind="false" pageable.bind="true" sortable.bind="true">
 </au-kendo-grid>
```

and the view model 
```javascript
export class BasicUse {
  datasource;

  constructor() {
    this.datasource = {
      type: "odata",
      serverFiltering: true,
      transport: {
        read: "//demos.telerik.com/kendo-ui/service/Northwind.svc/Customers"
      }
    };
  }
}
```


are not "in sync"

### Hints for next steps
- fix the above mentioned grid rendering
- note that the **[our basic grid sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/KendoUI-Grid-walthrough#our-basic-grid-sample)** is actually a slightly diminished version of [this Kendo sample](http://demos.telerik.com/kendo-ui/grid/index), where I took this template
```
                  template: "<div class='customer-photo'" +
                                    "style='background-image: url(../content/web/Customers/#:data.CustomerID#.jpg);'></div>" +
                                "<div class='customer-name'>#: ContactName #</div>",
```
from the definition of columns (because I did not have the customers images). See if you can add such template (and provide access to images) so that the wrapped grid renders like the original

![image](https://cloud.githubusercontent.com/assets/2712405/11611710/625bf1b0-9ba9-11e5-9735-9409fd1b7974.png)

**Comment by JeroenVinke** [comment]
We will document this as part of the grid performance improvements mentioned in [this issue](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/135)
