### ISSUE TITLE
expose Kendo events

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#123]
can we, or should we, do [this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/menu/menu.js#L54-L58) differently?

currently this raises a DOM event:

`<element select.delegate="doSomething()"></element>`

however, I'm worried that we get conflicts of existing html attributes. Is this a problem with custom elements or custom attributes?

**Comment by EisenbergEffect** [comment]
Perhaps consider namespacing the names. So you might have this instead:

```
<element kendo-select.delegate="doSomething()"></element>
```

**Comment by adriatic** [comment]
:-)
