### ISSUE TITLE
array of commands in au-col

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#125]
this
`<au-col command="['edit', 'destroy']" title="&nbsp;" width="250px"></au-col>`

generates this:

![image](https://cloud.githubusercontent.com/assets/2189477/11715568/2cd11a32-9f43-11e5-9a85-46f329e3b823.png)

**Comment by JeroenVinke** [comment]
unfortunately, since au-col is not a custom element, we can't do `command.bind` which would parse the array for us

**Comment by adriatic** [comment]
I believe that this is the good enough reason to pursue the implementation where the `<au-col>` **is** a custom element. 

Get ROb's opinion on this

**Comment by JeroenVinke** [comment]
The frozen columns sample also does not work because the column has a `locked` and `lockable` property which is a boolean. This breaks the grid, I believe because it is passed onto Kendo's grid as a string, when it expects a boolean

**Comment by adriatic** [comment]
For me - this is the final proof that our current implementation is sub-par :-(

**Comment by JeroenVinke** [comment]
fixed in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/165cd621469f73e1cfa53e096bebf45c70b52696
