### ISSUE TITLE
toolbar button redirects entire page

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#126]
when you click on this toolbar button:

![image](https://cloud.githubusercontent.com/assets/2189477/11715608/8465b83e-9f43-11e5-8265-f095bebdf8b6.png)

you get redirected to `http://localhost:3000/#` as this is the `href` of the button (it's an anchor)

**Comment by JeroenVinke** [comment]
http://www.telerik.com/forums/disable-grid-tool-bar-buttons#FR0IlcemTkOLMGrVds2N5g

**Comment by JeroenVinke** [comment]
I am not sure what is going on, but this now works...

**Comment by JeroenVinke** [comment]
@adriatic  can confirm that the toolbar button is working for you? this is on the working offline page

**Comment by adriatic** [comment]
It seems to work just fine (both `delete` and `update`) **I love this one**

**Comment by JeroenVinke** [comment]
great :+1:

**Comment by JeroenVinke** [comment]
wow!! this was fixed by changing `editable.bind="inline"` to `editable="inline"

**Comment by adriatic** [comment]
I did not read the initial problem report correctly
> you get redirected to http://localhost:3000/# as this is the href of the button (it's an anchor)

as I did observe that issue as well. Will try again after u do the pull
