### ISSUE TITLE
Aurelia templating integration

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#127]
Our initial implementation of KendoUI grid control "wrapper" class used a "hack" created to prevent Kendo from hijacking Aurelia interpolations:
```javascript
function parseCellTemplate(element, spec) {
  // Hack to avoid kendo hijacking Aurelia interpolations - need a good workaround for this
  if (element.childNodes.length > 0) {
    spec.template = element.innerHTML.replace(/\${/g, '!{');
  }
```
@JeroenVinke contacted Telerik and asked for the better way to do this. Here is Telerik's response:
> Hello Jeroen,
thank you very much for reaching out! Our team keeps an eye on the Aurelia project, so your activity sounds like great news.
Up to your question: I think that the easiest way to implement that would be through our **[AngularJS 1.* integration](http://www.telerik.com/blogs/announcing-angular-kendo-ui)**, which we use to compile the angular expressions when the widgets are used through Angular directives. Its implementation looks like this. If kendo.angular.js is not included, it is just a noop.
All kendo ui widgets have calls to it when templates are parsed and data items are added. The simplest widget where you can observe how it works is most probably the **[listview](http://demos.telerik.com/kendo-ui/listview/angular)**. In a nutshell, it calls the angular method with "compile" or "cleanup", and passes the context specific data items and DOM elements to it. I am not sure if this will fit the Aurelia case, though.
In case you need further assistance, feel free to reach out to my email - petyo.ivanov@telerik.com.
Regards,
Petyo

The actual implementation of Petyo's suggestion to use "Angular hooks", written by Jeroen is **[here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js)**

Since the Angular is hook is used by every Kendo control, and for every customizable template, Aurelia's templating system can now be used in all Kendo controls.

### Question for Rob
Is this a "good enough" solution?

**Comment by EisenbergEffect** [comment]
It's odd that they chose to name their api "angular" rather than providing a more general/generic API hook...but yeah this is probably good enough, assuming it works ;)
