### ISSUE TITLE
Current implementation of KendoUI Grid control wrapper needs further improvements

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#129]
Briefly stated KendoUI Grid control is implemented as a **[Custom Element](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js)**, that supports the following syntax:

```html
<au-kendo-grid data-source.bind="datasource" auto-bind.bind="false" pageable.bind="pageable" sortable.bind="true">
  <au-col title="Contact Name" field="ContactName">
    <div class='customer-photo' css="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
    <div class='customer-name'>${ContactName}</div>
  </au-col>
  <au-col title="Contact Name" field="ContactName"></au-col>
  <au-col title="Contact Title" field="ContactTitle"></au-col>
  <au-col title="Company Name" field="CompanyName"></au-col>
  <au-col field="Country"></au-col>
</au-kendo-grid>
```
This specific sample is rendered as 
![](http://i.imgur.com/rY5sTH2.png)

Our design uses the `<au-kendo-grid>` Custom Element with an "auxiliary" HTML tag `<au-col>` which are necessary and ~~sufficient~~ to completely define this sample grid and at the same time present the solution in the standard Aurelia way, consistent with Aurelia programming methodology.

Observe the word "sufficient" being deleted above - as a consequence of the recognition that this "one dimensional" implementation is not sufficient. By taking this approach we are only able to extract the information about grid columns (see **[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/children-parser.js)** for more details). A lot more important use case scenario:
```html
<au-col command="['edit', 'destroy']" title="&nbsp;" width="250px"></au-col>`
```
results with

![image](https://cloud.githubusercontent.com/assets/2189477/11715568/2cd11a32-9f43-11e5-9a85-46f329e3b823.png)

Since `<au-col>` is not a custom element, we cannot do `command.bind` which would parse the array ['edit', 'destroy'].

### Question for Rob
How do we best address this issue?

**Comment by EisenbergEffect** [comment]
There is an alternative way to handle this problem, which doesn't involve processing the content, but instead involves making use of custom elements and the `children` property type.

I'll try to make a quick example here, but if you've seen the tab-item demo I've showed here and there, it should be similar to that. The idea is that you create this:

```javascript
@processContent(compileColumnTemplate)
export class AuCol {
  @bindable title;
  @bindable field;
  @bindable command;

   ...
} 

That will represent the columns you have today. You should implement `compileColumntTemplate` to compile the column template that may be placed inside the element and pass the view factory along via the instruction to the column itself.

Then you create your grid element with all the props from before, but with one new one:

```javascript
export class AuKendoGrid {
  @children('au-col') columns;
}
```

This will take the view models that back the au-col elements you created and sync them into an array accessible via the columns property. Because these are custom elements, they can all be bound and thus your command property can use `.bind` and will contain an actual array at runtime. You will be able to access any custom grid templates on your view model, assuming you implemented the content processing to create the view factory and stored it as a property on the AuCol instance.

See if that makes sense.

**Comment by EisenbergEffect** [comment]
One other thing, you will need to implement a `<content></content>` placeholder in the view for this to work...so that the `au-col` elements have a place to go. You may want to wrap this in a div and give it a `display: none` since you are just using it for data, not for presentation.

**Comment by adriatic** [comment]
Thank you - without trying to immediately implement your idea, every word you wrote makes perfect sense. Knowing that the devil is in the details, I will wait until my tomorrow, when (I am sure) Jeroen will have it already in place (this young man is simply incredibly talented in my opinion).

While my question will show my insufficient knowledge of the "template compiler", but I will ask it nevertheless: can I expect that the compilation takes place just once (as different from from recompiling the template on each event like scrolling the grid)? This is most likely an impolite question, knowing how you do things :-)

**Comment by EisenbergEffect** [comment]
Yes, absolutely, the templates would be compiled once as part of the view compile and then that wouldn't need to happen per instantiation.

**Comment by EisenbergEffect** [comment]
Great question by the way.

**Comment by adriatic** [comment]
Let me remind you that million of years ago I led the incredibly talented team as the VP engineering at Visix Software inc. develop world's first non Sun implementation of Java (including it's Virtual Machine of course). So, I learned a lot about the "transition" form the trivial byte-code compiler, to a JIT compiler and techniques to make the interpreter run almost as fast as "compiled code".

This situation here is no different and given our (currently last) issue that deals with performance (https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/124, which I want to first "prepare" for you) my question is only natural :-)

**Comment by JeroenVinke** [comment]
Implemented in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/165cd621469f73e1cfa53e096bebf45c70b52696 and https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/a9bc94595b2575c786e5ffecf76db00a57d03428

**Comment by adriatic** [comment]
Jeroen - terrific job in refactoring grid wrapper to include **[Rob's advice](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/129#issuecomment-163802786)**

**Comment by EisenbergEffect** [comment]
@JeroenVinke An possible improvement you can make to your column processing:

```
@processContent((compiler, resources, element, instruction) => {
    let html = element.innerHTML;
    if (html !== '') {
      let fragment = DOM.createDocumentFragment();
      let current = element.firstChild;
      while(current) {
        fragment.appendChild(current);
        current = current.nextSibling || element.firstChild;
      }
      let factory = compiler.compile(fragment, resources);
      instruction.columnTemplateFactory = factory;     
    }

    return false;
})
```

This will extract the template out of the column element, if it exists and compile it into a view factory. If you do it here, then it happens once for the the view that the grid is contined within, redardless of how many times that view is instantiated. So, this is more efficient. (I haven't tested this code....)

**Comment by EisenbergEffect** [comment]
(DOM comes from aurelia-pal)

**Comment by adriatic** [comment]
> I haven't tested this code....

Consider this as a test :-)

**Comment by JeroenVinke** [comment]
@EisenbergEffect I should have explained why I didn't do template compilation in `@processContent`. Currently, we are passing the template of the column (as a string) to the grid [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js#L65). Kendo, before adding the `<tr>` elements to the DOM, is calling the `angular` callback and asks it to compile the `<tr>` element (which still contains the uncompiled column template). Since we now have a [template-compiler](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js) which handles all calls to the `angular` callback, I figured we didn't need this.

We did encounter performance issues in the `virtualization` example of the Grid. I don't know of any control other than the Grid that allows for virtualization, so perhaps it would be justified to look for alternatives hooks just for the row templates of the grid, so we can use the view-compiler instead of `enhance`.

**Comment by JeroenVinke** [comment]
wait a second, @EisenbergEffect, would the following be a possibilty?

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js#L53-L63

Kendo passes us an array of elements (`<tr>` tags) and dataItems (the `context`, in aurelia's terms). Can we perhaps use the view-compiler to generate a ViewFactory for the first `<tr>` and just change the binding context for each dataItem?

**Comment by JeroenVinke** [comment]
The implementation of the grid has changed, so this issue can be closed. We will look at peformance in another issue

**Comment by adriatic** [comment]
With the understanding that closed does not imply useless, I agree with closing it. I want to recycle parts of it for documentation purposes
