### ISSUE TITLE
Need a few more KendoUI controls "componentized" to get the sense for generic algorithm

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#13]
Given the accepted classification of KendoUI controls into two groups

- native HTML controls
- controls that do not have HTML native implementation

we have the **[rule](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Widget-Development-Guidelines#custom-elements-vs-custom-attributes)**  which determines whether a control will become a custom element or a custom attribute.

While we already have the first KendoUI control - **[AutoComplete](http://demos.telerik.com/kendo-ui/autocomplete/index)** **[implemented](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/src/autocomplete)** using Aurelia custom attributes, this control is not the generic representative of KendoUI controls that is converted to Aurelia component - meaning that the [autocomplete](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/src/autocomplete) cannot be used as a template for processing the rest of KendoUI controls.

**[DropDownList](http://demos.telerik.com/kendo-ui/dropdownlist/index)** adds more complexity as we need to create the children DOM elements - probably form an array of strings, using Aurelia HTML compiler -- and I would prefer to see Charles define the code for all such cases (including the controls that are not HTML natives like Grid).

There are several important issues:
- use Aurelia "production" compiler or the private branch Charles uses today
- definition of the utilities folder (to me made, with compiler being the first inhabitant)
- ...

that are all better to be decided by Charles

**Comment by JeroenVinke** [comment]
I believe that this issue is about the tamplating compilation, for which we have our own template-compiler now

**Comment by adriatic** [comment]
Good reasoning
