### ISSUE TITLE
Supporting themes

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#130]
I believe that we should try to squeeze the support for setting the theme in our demo app for the initial release.

![image](https://cloud.githubusercontent.com/assets/2712405/11731801/25d85af0-9f6c-11e5-981f-0b45a3f4f0dd.png)

This is even more important having in mind Aurelia Interface which will make this a prominent issue.

**Comment by JeroenVinke** [comment]
@adriatic Just to confirm, you are talking about supporting themes in the demo, not in the plugin, right?

**Comment by adriatic** [comment]
Yes of course. I would have done it long ago simply knowing how much would this do for the demo app. However this requires dynamic changes of the references to Kendo css files and I lost track of where these are accessed. Not all is perfect in this context, as for example the sample's `index.html` has this code
```html
    <link rel="stylesheet" href="jspm_packages/npm/font-awesome@4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="styles/styles.css">
```
probably because these two css files are needed "globally", when the same logic could be applied to Telerik's css files - and they are accessed somewhere else. 

This needs to be cleaned up and documented.

**Comment by JeroenVinke** [comment]
Font-awesome and `styles.css` are in the index.html because they are needed to show Aurelia's loading screen. The loading icon is coming from font-awesome, and the rest of the styling is coming from `styles.css`.

I remember that you have opened a issue somewhere, and that Rob explained a solution for something like this. No idea where I saw this though

**Comment by adriatic** [comment]
I do not remember that - and this whole issue is nearly irrelevant in the global "scene" - I just want to "instill the aim for perfection"

**Comment by JeroenVinke** [comment]
I understand, and I am not saying we have to implement this right away. I always like to have all available information registered in an issues, so it can be picked up whenever someone has time :) 

[this](https://github.com/aurelia/templating/issues/223#issuecomment-159650908) is what I was referencing to

**Comment by adriatic** [comment]
Well, your memory seems more persistent as I forgot this discussion with Rob (I liked it there and I like it still). So, I will assign this task to me as a reward!
