### ISSUE TITLE
Need to create cheat-sheets for all wrappers

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#131]
I just saw that you wrote the **[menu-wrapper](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/menu/menu.js)** and the **[basic-use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/menu/menu.js)** sample. That made me try to quickly whip up the next ("images") sample and that decision made me think that I should better document my coding for the benefit of others that follow. Being late as it is not, I decided to do this tomorrow - and this issue should sit here to remind us both on that task.

**Comment by JeroenVinke** [comment]
Plenty of examples, and seems to be easy enough for anyone to create a sample. We can provide more info when it is needed, but for now I don't see the need.
