### ISSUE TITLE
Slice error in inline sample

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#132]
![image](https://cloud.githubusercontent.com/assets/2189477/11746223/3b5214fa-a01d-11e5-8f57-5e2ae80ab123.png)

steps to reproduce:

1. open the working offline sample (grid)
2. click on edit in a row (notice the above error)
3. if you now click on "update" you get redirected to the about page

This error _could_ be causing https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/126

**Comment by adriatic** [comment]
My experience differs - but given the rapid pace of today's changes, I am preferring to wait until dust settles before returning to this again
