### ISSUE TITLE
Grid DetailInit proxy issue

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#133]
this:
`detailInit: (e) => fireKendoEvent(this.element, 'detail-init', e),`
results into this:
![image](https://cloud.githubusercontent.com/assets/2189477/11748997/70a7dbcc-a02b-11e5-968b-d93b34c634c7.png)

**Comment by JeroenVinke** [comment]
if you disable [this line](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/grid/grid.js#L105) then the icon disapears

**Comment by JeroenVinke** [comment]
I have disabled the event handler, until we can take a look at this

**Comment by adriatic** [comment]
Good - as I did not understand what is the purpose of `detailInit` anyway

**Comment by JeroenVinke** [comment]
Right, so angular handles events [here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L273-L281). They "proxy" events only if they are found as an attribute.

**Comment by adriatic** [comment]
Only now did I see a tiny red line indicating what (icon) disappears. This icon is a toggle to manage the detailed view od data owned by the person that is shown on that row.

**Comment by JeroenVinke** [comment]
oops!
