### ISSUE TITLE
Declaration of "bindables" should be sorted

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#134]
Using the grid.js wrapper as example. it is easy to see that the current "random" ordering of declarations makes it easier to to miss declaring an attribute as bindable - as it was with `height` attribute in grid.js wrapper

**Comment by adriatic** [comment]
Fixed grid.js - https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/6392bfef1f43932414cb6eb39a65a713c3c6a338

**Comment by JeroenVinke** [comment]
as this is now in our [componente checklist](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Component-checklist), can this be closed? before we release a wrapper we'll sort the bindables

**Comment by adriatic** [comment]
Yes, of course
