### ISSUE TITLE
Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#136]
This error message used to be "cannot dereference a null pointer" :-)
```
DEBUG [templating] importing resources for http://localhost:3000/src/grid/inline-editing.html []
kendo.core.min.js:9 Uncaught TypeError: Cannot read property 'slice' of nullve._extractFormat @ kendo.core.min.js:9a.extend.init @ kendo.numerictextbox.min.js:9(anonymous function) @ kendo.core.min.js:10jQuery.extend.each @ jquery.js:374jQuery.fn.jQuery.each @ jquery.js:139e.fn.(anonymous function) @ kendo.core.min.js:10w.number @ kendo.editable.min.js:9c.extend.editor @ kendo.editable.min.js:9c.extend.refresh @ kendo.editable.min.js:9c.extend.init @ kendo.editable.min.js:9ue.ui.DataBoundWidget.extend._createInlineEditor @ kendo.grid.min.js:10ue.ui.DataBoundWidget.extend.editRow @ kendo.grid.min.js:10(anonymous function) @ kendo.grid.min.js:10jQuery.event.dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121
```
This happens in the Grid [Inline editing example](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/grid/inline-editing.js), when clicking on the "Edit" button in any row.

**Comment by JeroenVinke** [comment]
Somehow, the "format" is null of the numerictextbox.

![image](https://cloud.githubusercontent.com/assets/2189477/11766180/b2f179d8-a17b-11e5-950d-c741f3d93638.png)

**Comment by JeroenVinke** [comment]
Good news though, it also happens when I disable our template-compiler, so it can't be caused by `enhance`

**Comment by JeroenVinke** [comment]
OK, when I provide a default value of `''`, even though the [docs](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.format) don't mention this, the issue is fixed

**Comment by adriatic** [comment]
Great fix
