### ISSUE TITLE
Frozen columns issues

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#137]
Two issues:

If you set `locked` of any column to `true`, the grid is completely empty:

![image](https://cloud.githubusercontent.com/assets/2189477/11766213/a56eb918-a17d-11e5-8108-af1e229d7cea.png)

if you don't set `locked` to true, and click the button in the header of the column:

![image](https://cloud.githubusercontent.com/assets/2189477/11766219/cfc085ac-a17d-11e5-85c8-1b370fc18505.png)

then it seems to pass a JQuery selector to our [enhanceView](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js#L68-L77) function:

![image](https://cloud.githubusercontent.com/assets/2189477/11766222/ed00b632-a17d-11e5-9b35-60b5bc4da602.png)

and because Aurelia's enhance function expects an `element` property:
![image](https://cloud.githubusercontent.com/assets/2189477/11766226/31d51564-a17e-11e5-85fb-5a7ed132e455.png)

 it gives us an error

![image](https://cloud.githubusercontent.com/assets/2189477/11766228/40225b2c-a17e-11e5-8bc9-d7d1bf6f5a0e.png)

**Comment by JeroenVinke** [comment]
issue number one could be related to [this](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.locked):

> Row template and detail features are not supported in combination with column locking.

**Comment by JeroenVinke** [comment]
issue number one was that the width of columns was passed in as a string:

`<au-col field="OrderID" title="Order ID" locked.bind="true" lockable.bind="false" width="150"></au-col>`

Changing this to use .bind:

`<au-col field="OrderID" title="Order ID" locked.bind="true" lockable.bind="false" width.bind="150"></au-col>`

fixed the issue. so it seems like when you use locked columns, it doesn't parse the width itself

**Comment by JeroenVinke** [comment]
issue number 2:

this is how our template-compiler is called:

![image](https://cloud.githubusercontent.com/assets/2189477/11766316/219d7250-a182-11e5-9df3-25ad0157726e.png)

**Comment by adriatic** [comment]
I do not think that I would solve this :-(

**Comment by JeroenVinke** [comment]
Can you explain? This solved it for me

**Comment by adriatic** [comment]
Given the fact that I am typing this with one finger on my iPad, I cannot look into anything

**Comment by JeroenVinke** [comment]
Even computers are unable to keep up with our pace.
Op 13 dec. 2015 17:25 schreef "Nikolaj Ivancic" <notifications@github.com>:
