### ISSUE TITLE
Using plugin config callback

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#14]
In my opinion, we should allow the consumer of the plugin to load only a subset of our plugins. Why globalize all resources when you may only use one widget?

It would look something like this:
```
aurelia.use
      .standardConfiguration()
      .developmentLogging()
      .plugin("aurelia-kendoUI", (config) => {
        config.useWidgets(["button", "grid"]);
      });
```

this would only globalize resources for the "button" and the "grid".

**Comment by charlespockert** [comment]
Sounds good, we could provide some defaults for all widgets that are in the core framework and another for all those in the pro framework to make it easier for people that just wanted access to everything

**Comment by JeroenVinke** [comment]
:+1: good one

@adriatic can you setup the organizational structure in github so that we can assign people to issues if needed? I also wonder who needs to agree with changes like this before we can start working on it

**Comment by adriatic** [comment]
On [setup the organizational structure](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/14#issuecomment-154987737) issue:

It's all in place actually - just not enabled.

**Comment by charlespockert** [comment]
FYI, I thought this was a no brainer so I've added it in this commit

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/c63949a7c6060c3b50fcbdd4affdb9885dd5859d

It expects a list of control names - e.g. `['button', 'grid', 'autocomplete']` etc. 

I'll leave this open for now as I want to add sensible defaults (e.g. core/pro defaults etc)

The reason we need this anyway is that the plugin attempts to load any resources that are globalized. This means it will throw an error on startup if it can't find the Kendo files for a particular plugin.

**Comment by charlespockert** [comment]
Also thinking it would be nice if the user could configure in a more strongly typed way, e.g. 

```
.plugin('aurelia-kendo', (plugins) => {     plugins.kendoGrid();
plugins.kendoButton():
});
```

Etc

**Comment by adriatic** [comment]
On [this comment](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/14#issuecomment-155152074)

**Comment by JeroenVinke** [comment]
@charlespockert already made an awesome plugin callback [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/0afb4dd25c035083052f4600e47d343442a07fc5) :smile:
