### ISSUE TITLE
Expand Best practices in using Aurelia KendoUI plugin article

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#142]
This article **[Best practices in using Aurelia KendoUI plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Best-practices-in-using-Aurelia-KendoUI-plugin)** has only the skeleton text.

Add all steps needed to create the **[basic use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/area-chart/basic-use.html)** sample

**Comment by JeroenVinke** [comment]
> I would like to see the "logic" behind the mapping of the KendoUI native attributes definitions and the definitions of the same data in the related Aurelia view-model, including the specifications of strings / integers (I believe that one can only specify strings in the view)

About the mapping: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/166
And the specification of strings/integer is mentioned [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/c98b19a8cd29e8c0f6e23f6694e08bbd25f9c8aa/sample/src/help/docs/app-developers-tutorials/what-you-need-to-know.md)
