### ISSUE TITLE
Aurelia_KendoUI demo app should act as a hub

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#143]
I would like to add a few pages (items on the main menubar):

**1. Documentation** that would fetch the selected set of articles from the wiki (see https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/141 for details)**

**2. Chat** that would show https://gitter.im/adriatic/Aurelia-KendoUI**

~~**3. "Feedback"" where people could "grade" the existing features and ask for new ones**~~

**Comment by JeroenVinke** [comment]
About 2: https://sidecar.gitter.im/

**Comment by JeroenVinke** [comment]
We should just use github for the third one

**Comment by adriatic** [comment]
> We should just use github for the third one

You mean the **[issues](https://github.com/aurelia-ui-toolkits/demo-kendo/issues)**, right?

**Comment by JeroenVinke** [comment]
Yes
Op 24 dec. 2015 16:05 schreef "Nikolaj Ivancic" <notifications@github.com>:

**Comment by JeroenVinke** [comment]
@adriatic if you agree, then I think this issue can be closed

**Comment by adriatic** [comment]
I agree
