### ISSUE TITLE
Proposal for the minimal design change for the sample app

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#145]
At the moment we need to make two changes to the current sample app design

1. Add support for showing the **complete** KendoUI **charts family**
2. Add support for showing the **complete** set of KendoUI **controls**.

**Note**: the change 2. naturally includes change 1. above - but since we want to create an Alpha release of the KendoUI plugin as soon as it is feasible, I am proposing such staged approach, which starts with item 1. above

***

##### Concept 1
![image](https://cloud.githubusercontent.com/assets/2712405/11795426/91205d9c-a284-11e5-918d-eab8c1fdcd84.png)

**Note**: one could say that we could simply replace the menubar "Area Chart" item with the DropDownList, I believe that this approach is more balanced than having the DropDownList "hang" on the menubar.

**Issue 1**: I would not like to invest more time in the current (Bootstrap based) menubar, which would be required to do it I want to show the DropDownList at the current "Area Chart" location.In that case it would be better to switch to Kendo menubar, without "showing it as a demo".

**Issue 2**. Even if we "resurrect" the existing KendoUI menu code, I do not know how to properly integrate it with Aurelia router so that the **[main app](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/app.js)** would work unchanged.

##### Concept 2

![image](https://cloud.githubusercontent.com/assets/2712405/11795982/c118b118-a287-11e5-8651-00aaae8ffd6f.png)

**Comment by JeroenVinke** [comment]
isn't this the same issue as [this one](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/139)? The question is: how will we allow users to navigate through all the samples, right?

**Comment by adriatic** [comment]
Correct - and again I would like to merge them having in mind that my most current proposal would be to have the most popular controls

![image](https://cloud.githubusercontent.com/assets/2712405/11903224/aa081292-a585-11e5-9eb0-82f9170d226f.png)

"listed" on the main manubar - so the user can access them directly, and then have the "control chooser" main menubar item that when clicked shows this popup

![image](https://cloud.githubusercontent.com/assets/2712405/11903276/0ad69e86-a586-11e5-998f-b284ef30179d.png)

**Comment by adriatic** [comment]
superseded by https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/206
