### ISSUE TITLE
The sample app should maintain the "currently selected demo" global variable

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#147]
Example:
- select the Line charts -> smooth line demo.
- then switch to Area charts -> smooth area demo
- switch back to Line charts - and the smooth line demo should still be selected

I am suggesting a single state variable - selected demo to be maintained, nothing more fancy to "save computation".

This state variable should be maintained across all demos of course - not just charts

**Comment by JeroenVinke** [comment]
If I would see this in an app, I would consider it as a bug, rather than a feature.

**Comment by adriatic** [comment]
Issue not worth arguing - as we see it too differently to find a common solution. When I will write my app, it will not reset itself on every click :-)
