### ISSUE TITLE
Chart wrapper should support the theme changes

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#149]
Briefly stated: `$(document).bind("kendo:skinChange", createChart);`

**Comment by JeroenVinke** [comment]
we can use Aurelia's EventAggregator for this. We can create a "theme selector" custom element, which publishes the "kendo:skinChange" event. And all chart samples subscribe to this event, and recreate the chart when this event is fired. See the samples in the [aurelia docs](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.3/doc/article/cheat-sheet)

**Comment by adriatic** [comment]
That is so Aurelian :-)

**Comment by JeroenVinke** [comment]
[this issue](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/130) is asking for the same, right?

**Comment by adriatic** [comment]
Yes, but I would prefer to merge them instead of removing one. This one explains **how** to do it, while the other one says **what** to do.

**Comment by JeroenVinke** [comment]
tried this:

```
return this.loader.loadText(`kendo-ui/styles/kendo.${theme}.min.css!`)
    .then(css => {
      if(this.styleNode) {
        DOM.removeNode(this.styleNode);
      }
      this.styleNode = DOM.injectStyles(css);
    });
```

but this doesn't work, because since the css is loaded as text (without the plugin-css SystemJS plugin), the paths inside the css file (such as images) are not transformed  . I got 404 errors this way, because it was looking for images in the wrong directory
