### ISSUE TITLE
we should host our own instance of kendo-ui-demos service

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#150]
Take it from here https://github.com/telerik/kendo-ui-demos-service, convert to node and host it somewhere.

The reason for this task is obvious - we want to make our sample app as much Aurelia app as we can afford - including data transport. This would be a great opportunity to show a full MEAN stack, where **A** stands for Aurelia.

**Comment by JeroenVinke** [comment]
Great find!!!

**Comment by JeroenVinke** [comment]
up and running for the samples that need it (such as signalr): http://kendo.jeroenvinke.nl

**Comment by adriatic** [comment]
Great. I care a lot about SignalR and plan to spend "there" a day or two as soon as I finish the initial doc pages ser
