### ISSUE TITLE
Find and install Kendo examples.css file

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#151]
Several samples (line charts - date axis for example) use additional UI like:

![image](https://cloud.githubusercontent.com/assets/2712405/11847800/25348328-a3ed-11e5-9ad4-74b2be2b01a0.png)

These radio button use classes like `<div class="box-col">` defined in the Telerik's `examples.css` file which seems hard to find :-). Here is Michael Graham's experience

http://www.telerik.com/forums/diagram-sample---box-col-style

**Comment by JeroenVinke** [comment]
http://demos.telerik.com/kendo-ui/content/shared/styles/examples.css

**Comment by adriatic** [comment]
Darn - I searched the whole internet - and this reference did not show anywhere. As this is a file that is specific to our sample app I am not sure where to stuff it so it does not get lost.

Any idea?

**Comment by JeroenVinke** [comment]
I would put this in the styles folder of the sample app [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample/styles). That way, it's copied when updating our demo site.

**Comment by adriatic** [comment]
Done - and the UI controls are layed out correctly
