### ISSUE TITLE
All chart description sections need to be updated to Aurelia environment

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#153]

**Comment by JeroenVinke** [comment]
Can you explain what you mean by this?

**Comment by adriatic** [comment]
Sure - all current descriptions are written for "old JavaScript" and have no references to our Aurelia Custom Element based implementation. A good example is this section from Bubble Chart:

> To instantiate a Kendo UI chart, you need to specify an empty div with an id on the page, select this div with a jQuery selector and invoke the kendoChart() function. As a result, the chart is registered as a standard jQuery plugin.

**Comment by JeroenVinke** [comment]
it's a lot of work to add this for all the samples

**Comment by adriatic** [comment]
While this is true, we could either do it right or not at all (meaning that we should remove the `description` tab until we have the time to do this right, right}?

**Comment by JeroenVinke** [comment]
what do you think?

**Comment by adriatic** [comment]
I would delete this `li` element

![image](https://cloud.githubusercontent.com/assets/2712405/11908717/a9792722-a5ac-11e5-95d8-8ced4dabf445.png)

**Comment by JeroenVinke** [comment]
:+1:

**Comment by JeroenVinke** [comment]
do we still need this issue? I guess we don't have to add descriptions to every control right away, just the ones that are "complex" or have a cool implementation

**Comment by adriatic** [comment]
> just the ones that are "complex" or have a cool implementation

That would be my approach, yes - at least initially. Telerik has consistently written something (even it is a many times used repeat) in all samples, probably with the intent to keep the user feeling safe :-)
