### ISSUE TITLE
box-plot charts -> binding to remote data does not read the ozone.json file 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#155]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/box-plot-charts/binding-to-remote-data.html

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/box-plot-charts/json/ozone.json

Is the problem caused by the nesting in the `json` file

**Comment by JeroenVinke** [comment]
found it! :)

**Comment by adriatic** [comment]
Smart man :-) (I always find other people's bugs and seldom my own)
