### ISSUE TITLE
bubble charts issues

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#156]
1. Basic use case - wrong position of the y-axis
2. Binding to remote data - missing y-axis title
3. binding to local data - wrong position of the y-axis
4. Binding to grouped data:

![image](https://cloud.githubusercontent.com/assets/2712405/11901933/541afd9e-a57c-11e5-9502-471ce70f1e5a.png)

should be like this

![image](https://cloud.githubusercontent.com/assets/2712405/11901924/4474f390-a57c-11e5-819e-f9b2486eec3d.png)

**Comment by JeroenVinke** [comment]
:)
