### ISSUE TITLE
need to support setting chart background

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#157]
Example: http://demos.telerik.com/kendo-ui/donut-charts/index

**Comment by JeroenVinke** [comment]
this may be the same problem as https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/161, because they override the transparent background color on the `<div>` the chart is initialized on. We can't do this, because our wrapper is "shielding" this div from us

```
div.k-chart, div.k-gauge, span.k-sparkline, .k-stockchart {
    background-color: transparent;
}
```
