### ISSUE TITLE
Check for consistent layout 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#163]
1. all samples should live in  `<div class="demo-section k-content">` More precisely - all samples should use all needed css classes defined in **[samples.css](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/styles/samples.css)**
2. All views should be formatted as shown below:
```html
<template>
    <k-chart    title.bind="{text: 'Gross Domestic product growth \n /GDP annual %/'}"
                legend.bind="{position: 'bottom'}"
                series-defaults.bind="seriesDefaults"
                series.bind="series"
                value-axis.bind="valueAxis"
                category-axis.bind="categoryAxis"
                tooltip.bind="tooltip">
    </k-chart>
</template>

meaning that all attributes are at the same tab stop following the custom element's name

**Comment by JeroenVinke** [comment]
We can put `<div class="demo-section k-content">` around the `compose` tag in our [`sample-runner.html`](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/sample-runner.html#L4). That way, it is applied to all the samples, without having to put this stuff in every one of them :)

**Comment by JeroenVinke** [comment]
actually, we can't do what I wrote above, because this is different per sample.

So we have to check every sample and add the appropriate div's

**Comment by adriatic** [comment]
> So we have to check every sample and add the appropriate div's

That is what I did yesterday (my changes are not yet pushed in)

**Comment by JeroenVinke** [comment]
fixed via https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/1d830d0451d3653e770f07a20407457d7723d7bc
