### ISSUE TITLE
style selector panel is not always accessible

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#167]
Dependent on the browser width, right side of the selector is truncated as shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/11920053/b6553670-a732-11e5-9334-25998861968f.png)

Possible solutions
1. Implement the style selector the same way as the sample selector
2. Place the current style selector item as the first item on the menubar (this looks silly)
3. Ensure that the current selector always fits the window (not sure whether this is possible)

**Comment by JeroenVinke** [comment]
I have thought of using aurelia-dialog for this. That way, you can still
see the immediate change of the active theme. We can also use a dialog for
the sample selector. That way, you won't have to switch back and forth
between the sample selector and the sample's themselves. What do you think?
Op 20 dec. 2015 22:02 schreef "Nikolaj Ivancic" <notifications@github.com>:

**Comment by adriatic** [comment]
> ... you can still see the immediate change of the active theme

**This is definitively the proper argument to use Aurelia dialog**, yes - with eventual upgrade to Kendo's equivalent if it exists. I do not necessarily want to be a bigger saint than the pope - we are already happily using elements of Bootstrap in our app, so assuming we use the proper reasons for deciding what to use internally, that is just fine. For example, I was planning to use carousel to "proudly show" the most representative KendoUI controls 

![image](https://cloud.githubusercontent.com/assets/2712405/11920148/fe7d8d9c-a734-11e5-9c8c-a84e17ca012c.png)

**Comment by adriatic** [comment]
Another comment on **[using Aurelia dialog](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/167#issuecomment-166155041)**:

The argument ***We can also use a dialog for the sample selector. That way, you won't have to switch back and forth between the sample selector and the sample's themselves*** does not hold the same weight as in the case of the theme selector, since it is bigger and you see the effects of selecting the specific sample by switching the whole page anyway. This is different from the theme selector situation where you want to see the immediate effect of the theme change "underneath" the theme selector.

To be really nitpicky - in order to see the immediate effect of the theme selector, we would have to react on the hover event on the selector, which will not dismiss the selector itself - and that behavior would be unexpected by most people.

**Comment by JeroenVinke** [comment]
What do you propose? Use the dialog for the themes, and keep the sample selector the way it is now?

**Comment by adriatic** [comment]
## YES

**Comment by JeroenVinke** [comment]
Just tried this,  but unfortunately the dialog has the same problem, it doesn't resize and you can't move the dialog

**Comment by adriatic** [comment]
The (obvious) alternative is to use KendoUI dialog :-)

**Comment by JeroenVinke** [comment]
@adriatic I think you're going to like this one :)

**Comment by adriatic** [comment]
## Love it

Thank you.
