### ISSUE TITLE
funnel-charts funnel-labels sample needs slider control

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#169]
See http://demos.telerik.com/kendo-ui/funnel-charts/funnel-labels

![image](https://cloud.githubusercontent.com/assets/2712405/11920839/d380abf8-a746-11e5-8fbb-d22489fccf5e.png)

**Comment by adriatic** [comment]
We need to decide how to use this slider in this context - do we "buffer" the slider events and do refresh when the user ends the drag, or do we refresh after each slider moved event? I worry that the second option might behave "jerky"

**Comment by charlespockert** [comment]
You can probably use the new binding behaviors to achieve throttling which
is what you want.

**Comment by JeroenVinke** [comment]
Do we even need to buffer the sliding events? I believe the `change` event of the slider is only called after the user lets go of the slider?

**Comment by JeroenVinke** [comment]
> You can probably use the new binding behaviors to achieve throttling which
is what you want.

or we can try that ;)

**Comment by adriatic** [comment]
> Do we even need to buffer the sliding events? I believe the change event of the slider is only called after the user lets go of the slider?

I believe that you are right - I am about to start hooking the "user generated event" with view models across all of "my" charts where I left that undone

**Comment by adriatic** [comment]
Of course when you say 

> You can probably use the new binding behaviors to achieve throttling which
is what you want.

it means to me as little as 

縓罃蔾 褣諝趥 纑臞蘬 稯 墏壾 嶝仉圠 浞浧浵 瓥籪 踙, 鞮鞢騉 匢奾灱 驧鬤鸕 裌覅 諙 鑗鱐 簻臗藱 驧鬤鸕 榬榼榳 暕 鑏鑆驈 蠬襱覾 狅妵妶 馺 獝瘝, 蝺 駍駔鳿 毄滱漮 灂瀿 蝺 厹屴 輑鄟銆 痑祣筇 罫蓱蒆, 錖霒馞 蛚袲褁 濷瓂癚 筡 鞁鬿 蔉蔪 髬 腠腶舝 碄碆碃, 蝯 喥喓堮 羳蟪蠁 鋑鋡, 鸋齸 穊 齈龘墻 鳻嶬幧 笢笣紽

**Comment by charlespockert** [comment]
http://www.danyow.net/aurelia-binding-behaviors/

Info there, check out the throttling and debounce

**Comment by adriatic** [comment]
@charlespockert thanks!

Both you and Jeroen should feed me with such morsels, while I still want to go through (what some call) Aurelia documentation,

**Comment by charlespockert** [comment]
I think @jeroenvinke is right though, I think the Kendo API only updates the value when you release the mouse.

**Comment by adriatic** [comment]
Thanks for https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/169#issuecomment-166976158 - nice features, very clear article
