### ISSUE TITLE
How finished is the TabStrip control

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#17]
Looking at Telerik's [TabStrip documentation](http://docs.telerik.com/kendo-ui/web/tabstrip/overview) I just got reminded that we have to support both declarative and programmatic style to define controls. The [current implementation](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/tabstrip/tabstrip.js) seems to be ready to handle both style, so in order to demonstrate that the code in the [tabstrip folder](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample/src/tabstrip) needs to be augmented to match the features shown on the [original demo](http://demos.telerik.com/kendo-ui/tabstrip/index)

![image](https://cloud.githubusercontent.com/assets/2712405/11103700/197072c0-8892-11e5-9f9a-648727a22577.png)

Seeing this screenshot raises the question that I am really curious about: having done the Aureliaization of the KendoUI tabstrip, is the [Loading content with AJAX](http://demos.telerik.com/kendo-ui/tabstrip/ajax) even relevant in this context - or (as I hope) this comes as a side-effect of having this control "converted" to Aurelia control?

**Comment by adriatic** [comment]
While I will wait for some feedback on this [Loading content with AJAX](http://demos.telerik.com/kendo-ui/tabstrip/ajax) question, I will also finish this control.

**Comment by charlespockert** [comment]
Some work is involved to ensure all the use cases are covered but I'd say it's at least a percentage complete (basic use works fine). I'll look at working on this at some point later this week

**Comment by JeroenVinke** [comment]
Issue is pretty old, and the tabstrip is not included in this release, so we'll take another look when we pick this control up
