### ISSUE TITLE
Donut chart does not respond to theme change event

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#171]
The only code I found that deal with specific controls is **[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/shared/theme-manager.js#L22)** - but this does not seem to explain why the donut chart acts differently

**Comment by JeroenVinke** [comment]
You have found the code that does this, yes. Telerik uses the exact same code to set the theme property of each control. 

Telerik's sample has the same issue though: http://demos.telerik.com/kendo-ui/donut-charts/index

**Comment by adriatic** [comment]
Telerik's sample does not have that issue - as shown below in Material Black Theme:

![image](https://cloud.githubusercontent.com/assets/2712405/11947716/e2b97c56-a838-11e5-9356-329a2e9667cb.png)

In our implementation, other Donut contros behave properly with respect to the theme changes, most likely indicating that our definition of the background
```html
style="background: center no-repeat url('http://demos.telerik.com/kendo-ui/content/shared/styles/world-map.png');"
```
prevents the theme change.

**Comment by JeroenVinke** [comment]
Sorry, didn't know you were talking about the background, and not the donut itself :)

**Comment by JeroenVinke** [comment]
it's because we didn't have the appropriate div's surrounding our sample as mentioned [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/163)
