### ISSUE TITLE
Generate event "proxies"

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#172]
Each component has an array of supported events

![image](https://cloud.githubusercontent.com/assets/2189477/11927458/e7af78ee-a7cc-11e5-94ff-dd143233fffc.png)

from which we can generate this code:

![image](https://cloud.githubusercontent.com/assets/2189477/11927470/fc91fc64-a7cc-11e5-985f-86017f340252.png)

`kendo.ui.AutoComplete.prototype.events` gives us the array of all "AutoComplete" events

**Comment by adriatic** [comment]
Very cool.
