### ISSUE TITLE
Generate bindable properties

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#173]
Instead of manually creating bindable properties from the Telerik docs (which have been unreliable before), we can perhaps generate the bindable properties from the `options` inside each control:

![image](https://cloud.githubusercontent.com/assets/2189477/11927644/5013d442-a7ce-11e5-9395-cb168f016d02.png)

**Comment by adriatic** [comment]
Show me how would this look in actual use - say on a complex chart sample

**Comment by JeroenVinke** [comment]
**This is pure theory**

On initialization of a control, we retrieve the `options` object of the control we want to initialize, shown in the image above.

Then we loop over all the properties, and create `BindableProperty` instances for each one of them. The `@bindable` decorator is actually creating these `BindableProperty`'s for you, but we would generate these from the `options` object.

We would be able to get rid of this:
![image](https://cloud.githubusercontent.com/assets/2189477/11935198/d6a84c08-a806-11e5-9d35-4e6e8abdb7cb.png)

As the default values are in the `options` object as well, we won't have to look those up either anymore

**Comment by adriatic** [comment]
In addition to being pure theory, it also seems like a good theory. What you are doing now is wonderful and was always area of my interest: simplify the language (or API) which is particularly fun to do in the realm of javascript.

**Comment by charlespockert** [comment]
Good idea, this also means that bindables will be automatically generated
for new properties when the kendo framework is updated

I'm all for this!
