### ISSUE TITLE
Design the basic structure of AKP documentation

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#174]
The title implies both the structure of the information ~~and the tools for search and presenting that data~~

**Comment by adriatic** [comment]
I want to cover the following area (not necessarily in this order), where most of the "titles" below have sub-items:

- Introduction to Aurelia
- Introduction to KendoUI
- Basics of writing Aurelia plugins
- Writing Aurelia plugin tutorial
- How to use Aurelia-KendoUI bridge
- Tutorial: writing a real Aurelia app using Aurelia KendoUI bridge

**Comment by adriatic** [comment]
We should also use the **[KendoUI Treeview](http://demos.telerik.com/kendo-ui/treeview/index)** control to host the information 

![image](https://cloud.githubusercontent.com/assets/2712405/11980227/53e9c988-a967-11e5-8af5-f41f1dddc6da.png)

**Comment by adriatic** [comment]
### Update

We do not need to spend any time on rolling our own documentation UI, as we will soon have Aurelia's own UI available:

> I think that you will be able to use our help tech very soon. Basically, we are going to be adding docs to our docs on how to write docs  So, that will be available soon and show you how it works Basically, it's markdown+metadata+custom elements. One nice thing is that if you put a doc folder in your repo and follow our layout, you will be able to use our hosted app to view your docs by simply putting the correct hash fragment in our app
I'll get you further details soon.

Since I am not sure what "soon" really means and not wanting to wait even for a day, I would propose to Jeroen to just create two panels, both being our markdown custom elements, where the left one extracts the "Doc index" from **[doc folder](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/doc)** (note that at this moment I do not know what is the purpose of the **[api.json](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/doc/api.json)** file and whether it can be used to also host the doc **index data**.

In order not to spend too much efforts on this "workaround" Documentation User Interface) all I need really is that left panel that scans the folder with all user documents, renders this as a list and that the click on each list element, renders the content of the .md file associated with that list element. 

That will allow me to completely focus on the documentation, leaving even some of my charts unfinished as I want to describe all of the "tricks" used to make Kendo controls interactive (like **[tree map](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample/src/charts/treemap)** for example)

**Comment by JeroenVinke** [comment]
:+1:

**Comment by JeroenVinke** [comment]
implemented in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/38fbdc15f919180ff64b0ea6b35b139b0afa55ed

**Comment by adriatic** [comment]
Nice

**Comment by adriatic** [comment]
At this point, we have sufficiently strong set of features needed to write markdown docs.
