### ISSUE TITLE
Sparkline does not support type

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#177]
in [this sample](http://demos.telerik.com/kendo-ui/sparklines/index), sparklines are initialized with a "type":

```
$("#stats-mon").kendoSparkline({
    type: "pie",
    data: [14, 10]
});
```

This type property does not exist in the `options` of the kendoSparkline control:

![image](https://cloud.githubusercontent.com/assets/2189477/11951815/62db19de-a894-11e5-804a-f1f43ccde6e2.png)

which means that bindable properties are not generated for the type.

Just tested this out in angular, and it doesn't work there either. 

```
          <div kendo-sparkline
                 k-data="[8, 16,15,2,3,3,3,2,4,6,624,634,634,3,3]"
                 k-type="pie"></div>
```

renders nothing while

```
            <div kendo-sparkline
                 k-data="[8, 16,15,2,3,3,3,2,4,6,624,634,634,3,3]"></div>
```

renders

![image](https://cloud.githubusercontent.com/assets/2189477/11951830/8cc26aa4-a894-11e5-96d7-19db48af056c.png)

"dataSource" is also "missing" from these options properties, but angular handles this one manually. This is not the case with sparkline. We can probably let our wrappers supply additional fields to create bindables for, and by default this contains the `dataSource` property

**Comment by JeroenVinke** [comment]
Right, so angular's implementation is doing this stuff a bit different.

**How we do it now**
From the `options` object in a Kendo widget ([example](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.button.js#L68-L74), we generate the BindableProperty's, and set the values of these properties to the ones out of the `options` object. Then when we initialize the Kendo control, we pass the **entire** options object.

** How angular-kendo does this **
Just before a Kendo control is initialized, the attributes on the element are iterated over ([here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L266-L302)). Only the attributes that are found on the element are passed when initializing the control.

So for example, when we use this:

```
<button au-kendo-button></button>
```

we initialize the control with:
```
$(this.target).kendoButton({
            name: "Button",
            icon: "",
            spriteCssClass: "",
            imageUrl: "",
            enable: true
});
```

while angular does this:
```
$(this.target).kendoButton({});
```

As mentioned in the above post, not all possible options of a control are defined in the `options` object (such as [this one](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.button.js#L68-L74)). Even though it contains the majority of the options, some are missing, and we will likely run into more of these issues.

**Comment by adriatic** [comment]
The **[premise of this discussion](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/177#issue-123444400)** may not be correct in the strict sense, despite the code that says
```
$("#stats-mon").kendoSparkline({
    type: "pie",
    data: [14, 10]
});
```
because the object being rendered 

![image](https://cloud.githubusercontent.com/assets/2712405/11969032/0479290a-a8e2-11e5-8fae-8830447b8c93.png)

is **not a sparkline** - it is a **pie chart** as shown on **[this page](http://demos.telerik.com/kendo-ui/pie-charts/remote-data-binding)**

The fact that this sample with the mix of sparkline and pie charts is a consequence of some "dirty" trick that allows dropping such cuckoo egg (a pie) into the sparkline control.

Unless this is a published feature instead a dirty trick (question for Petyo, I guess) we should not support that (I might be overridden here here as a purist)

**Comment by JeroenVinke** [comment]
@underlog Hey Petyo,

Can you comment on the message of @adriatic above?

This doesn't work in angular-kendo either:

```
          <div kendo-sparkline
                 k-data="[8, 16,15,2,3,3,3,2,4,6,624,634,634,3,3]"
                 k-type="pie"></div>
```

If that is a correct usage of the sparkline control, shouldn't the `options` object inside the `kendoSparkline` widget contain a `data` and a `type` property?

![image](https://cloud.githubusercontent.com/assets/2189477/11974792/ca571256-a967-11e5-8789-7b3e98674d93.png)

Thanks!

**Comment by JeroenVinke** [comment]
Got it. `data` and `type` are properties of the `series` array. 

So this: 
`<k-sparkline k-data.bind="[14,10]" k-type="pie"/>` 
becomes 
`<k-sparkline k-series.bind="[{ type: 'pie', data: [14,10] }]"/>`

**Comment by adriatic** [comment]
> Got it. `data` and `type` are properties of the `series` array

Smart conclusion!!
