### ISSUE TITLE
Make registry more generic

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#184]
A slightly different use case scenario will make our sample a lot more appealing

![image](https://cloud.githubusercontent.com/assets/2712405/11962705/dc7eb956-a8af-11e5-9fdb-357b7521fb57.png)

The **Docs** is one of the two tabs on the help page

![image](https://cloud.githubusercontent.com/assets/2712405/11962723/125067aa-a8b0-11e5-98f6-b2132948c7b0.png)

This can be achieved by a slight change like replacing "samples" with "items" in 
```
{
  "title": "Autocomplete",
  "samples": {
    "api": {
      "title": "API",
      "files": ["html", "js", "css"]
    },
    "basic-use": {
      "route": ["", "basic-use"]
    },
    "customizing-templates": {
      "files": ["html", "js", "css"]
    },
    "events": {},
    "remote-data": {},
    "virtualization": {}
  }
}
```
Not sure yet what would be required to properly set the accordion up - but accordion could be a welcome replacement for the current "list" when the number if items requires scrolling; this is particularly true once realizing that the sidebar does not have its own scrollbar

**Comment by JeroenVinke** [comment]
@adriatic how many documents are we actually going to put there?

Perhaps we can use the kendo-grid to show all the documents, with a button that links to a page that shows the actual document. If we use the kendo-grid, pagination/search is included automatically :)

**Comment by adriatic** [comment]
**As many as it takes** would be an unpolite reply, so I would rather say how my intent is not to save my efforts by creating too little. I want to cover the following area (not necessarily in this order), where most of the "titles" below have sub-items:

- Introduction to Aurelia
- Introduction to KendoUI
- Basics of writing Aurelia plugins
- Writing Aurelia plugin tutorial
- How to use Aurelia-KendoUI bridge
- Tutorial: writing a real Aurelia app using Aurelia KendoUI bridge

**Comment by adriatic** [comment]
> Perhaps we can use the kendo-grid to show all the documents.

I think that **[TreeList](http://demos.telerik.com/kendo-ui/treelist/remote-data-binding)** would be a better fit - and either way, using a KendoUI control in this context is a lot better approach that using our sidebar. Thanks for thinking for me :-)

If we agree on this approach, I could whip up the TreeList wrapper with minimal functionality we need here:

![image](https://cloud.githubusercontent.com/assets/2712405/11978684/7019b16a-a95b-11e5-8f40-d30ca1f8e751.png)

**Comment by JeroenVinke** [comment]
I don't think you can select a row in a treelist :(

**Comment by adriatic** [comment]
## WHAT??

**Comment by adriatic** [comment]
Check http://demos.telerik.com/kendo-ui/treeview/events

**Comment by JeroenVinke** [comment]
That's the treeview, not the treelist :) But OK, that should work just fine :)

**Comment by adriatic** [comment]
:-)

**Comment by adriatic** [comment]
This item is superseded by https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/174
