### ISSUE TITLE
Instantiating multiple controls from the view-model

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#185]
I have not had the chance to grasp the conversation between @JeroenVinke and @charlespockert on supporting KendoUI API - which I hope will bring the support to use programmatic interface to KendoUI from any Aurelia component.

With this caveat here is a **[good example](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/pie-charts/binding-to-remote-data.html)** that is begging for programmatic interface.

**Note**: @JeroenVinke can you show me how would you bind this sample with the data that is already available in it view model. Not being sure how to have a single invocation of the datasource (which feeds all 10 instances of the pie chart) while having the filter object which is a part of the datasource feed the proper to each pie instance

**Comment by JeroenVinke** [comment]
Alright, so "**instantiating** controls from the view-model" is actually not something we should support, IMO. We create "html api's" so people can instantiate Kendo controls from HTML, without the hassle of **initializing** the control from the view-model. 

Let's say someone has a plain div, and a button. When the user clicks on the button,  a kendo grid should get initialized on the div. Now, is this something our wrappers should be used for? Or should the developer just use `jQuery(this.div).kendoGrid()`?. I think the latter is the only way of doing this.

> Note: @JeroenVinke can you show me how would you bind this sample with the data that is already available in it view model. Not being sure how to have a single invocation of the datasource (which feeds all 10 instances of the pie chart) while having the filter object which is a part of the datasource feed the proper to each pie instance

I have an idea how this could be done.

**Comment by adriatic** [comment]
> Or should the developer just use jQuery(this.div).kendoGrid()?. I think the latter is the only way of doing this.

That is the right way - trying to go beyond that is making little sense, I agree, at least not until the whole KendoUI is rewritten in Aurelia (this is me projecting the amount of enthusiasm for Aurelia, Kendo team will develop once they become aware of it via our Aurelia-KendoUI project)
