### ISSUE TITLE
Embedding gitter side car inside a tab 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#186]
Here is the code that Gitter specifies as sufficient and necessary to embed Gitter
```
          <script>
              ((window.gitter = {}).chat = {}).options = {
                room: 'adriatic/Aurelia-KendoUI'
              };
          </script>
        <script src="https://sidecar.gitter.im/dist/sidecar.v1.js" async defer></script>
```

Now given that the page I want to have this instantiated is not any ordinary Javascript, **it is obvious that I need some Aurelia specific guidance**. By the way, this is one of the basic questions we would like to cover in our Help docs I am trying to build.

**Comment by JeroenVinke** [comment]
I'll see if we can create a custom element for this. Perhaps we can put this custom element in a plugin, so it can be used by anyone :)

**Comment by adriatic** [comment]
This is a **great** idea - can't wait to get my fingers on it

**Comment by JeroenVinke** [comment]
done https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/af7953aa7a74dd1e3b98c876b346ac0d5201bb88

**Comment by adriatic** [comment]
... I was just about to ping you via getter and ask about some ETA on that !!!
