### ISSUE TITLE
Setting the style in the view-model has no effect

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#189]

**Comment by JeroenVinke** [comment]
how do you mean?

**Comment by adriatic** [comment]
The same style (say setting the width of the control) when moved from the view to view model - would not change the width

**Comment by JeroenVinke** [comment]
Ah ok, which control are we talking about?

**Comment by adriatic** [comment]
Apologies for being cryptic - I had to make a run to a store, so I hoped you would know what I am talking about without typing more information and having my head to be cut off :-)

Use the **[pie charts - binding to remote data](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/pie-charts/binding-to-remote-data.html)** to verify this - and in order to do least amount of typing, comment out all pie control instances except one. Then move the style attribute definition from the control declaration in the model
```
style= "height: 120px; width: 125px"
```

into the view model to be:
```
export class BindingToRemoteData {
    dataSource = new kendo.data.DataSource({
        transport: {
          read: function(options) {
            return System.import('charts/pie-charts/json/screen_resolution.json!json')
            .then(data => options.success(data));
          }
        },
        filter: {
            field: "year", operator: "eq", value: 2000
        },
        sort: {
            field: "year",
            dir: "asc"
        }
    });

    style = "height: 120px; width: 125px";

    title = {
        text: 2000
    };
...
```

**Comment by JeroenVinke** [comment]
try this:

```
            <au-kendo-chart title.bind="title"
                          **css.bind="css"**
                          data-source.bind="dataSource"
                          legend.bind="legend"
                          series-defaults.bind="seriesDefaults"
                          series.bind="series"
                          tooltip.bind="tooltip">
            </au-kendo-chart>
```

**Comment by adriatic** [comment]
... and what is the definition of the **css** attribute in the view model?

**Comment by JeroenVinke** [comment]
what you had before: `style = "height: 120px; width: 125px";`

**Comment by JeroenVinke** [comment]
oh sorry, that should be `css.bind="style"`

**Comment by adriatic** [comment]
Oh, OK - you are saying that the style definition has to be in the css file (not view model aka ..js - and just in the last second you prevented me from asking "how the heck do I define the name of the .css file :-)

**Comment by adriatic** [comment]
You also learned that you cannot make words **bold* in the 
```
<au-kendo-chart title.bind="title"
                          **css.bind="css"**
                          data-source.bind="dataSource"
                          legend.bind="legend"
                          series-defaults.bind="seriesDefaults"
                          series.bind="series"
                          tooltip.bind="tooltip">
</au-kendo-chart>
```

**Comment by JeroenVinke** [comment]
> You also learned that you cannot make words *bold in the

I did! haha

> Oh, OK - you are saying that the style definition has to be in the css file (not view model aka ..js - and just in the last second you prevented me from asking "how the heck do I define the name of the .css file :-)

oh right, you could actually just use css for that. Just create a .css file:

```
au-kendo-chart {
height: 120px; 
width: 125px
}
```

then import it via `<require from="./style.css"></require>`

**Comment by adriatic** [comment]
... and remember to fix the related `registry.json` file !

**Comment by JeroenVinke** [comment]
Yep!

**Comment by adriatic** [comment]
Since we are in the context of that pie chart sample where I am still expecting to see your idea mentioned in [your comment](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/185#issuecomment-166861696)

**Comment by JeroenVinke** [comment]
Ofcourse: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/9c92d794a4d3d33ea2fdbbceae257ccbe5ce3dc1

**Comment by adriatic** [comment]
It really bugs me how simple this is and how I still feel "frozen" in this context (declarative programming, ES7 attributes, etc. :-(

**Comment by JeroenVinke** [comment]
Well, if I didn't see this before, or knew that this was possible, I wouldn't have done this either ;)

**Comment by adriatic** [comment]
Well, I saw nothing of it, still have not learned anything about ES6, this sample app is my first aurelia app (other than messing up with morphing the Navigation Skeleton) etc.

All this is about to change as I am starting https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/187 ASAP
