### ISSUE TITLE
Width of demo content is not correct

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#190]
In the auto complete sample (customizing templates for example), the width of the autocomplete control is not equal to the width the autocomplete has in the telerik sample. Not sure why

**ours**
![image](https://cloud.githubusercontent.com/assets/2189477/11982197/5e8d5c28-a9a9-11e5-8b04-6e4dfddfa43b.png)

**Telerik's**
![image](https://cloud.githubusercontent.com/assets/2189477/11982208/75ae0dc6-a9a9-11e5-95f0-9b6a0b1a3918.png)

@adriatic can you check this out?

**Comment by adriatic** [comment]
It has to be the consequence of our a bit inconsistent use of KendoUI "classes" (css files)

**Comment by JeroenVinke** [comment]
Can't find the cause though, as the divs are correct
