### ISSUE TITLE
Shorten names

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#191]
`<au-kendo-dropdown-list>` becomes `k-dropdown-list`

**Comment by adriatic** [comment]
Are you doing this for all controls in a single sweep? I would not pull anything until you are done

**Comment by JeroenVinke** [comment]
Probably, yes. it's better to get it over with. You can always create a branch from master, work in there and push your changes to that branch. Then we can merge your changes in when time is right :)

**Comment by adriatic** [comment]
This begs the question: where do you usually create the branch - on Github desktop or on Github using the browser

**Comment by JeroenVinke** [comment]
Desktop client is easiest

![image](https://cloud.githubusercontent.com/assets/2189477/11983252/71578fdc-a9b2-11e5-85b1-5a87fe588c9e.png)

**Comment by JeroenVinke** [comment]
@adriatic I'm done anyway, so if you should be fine to just pull

**Comment by adriatic** [comment]
Question: I believe that you said how you use Atom - so do you make such massive change just using `global find and replace`?

**Comment by JeroenVinke** [comment]
Yep, just right click on a directory and use "search in directory"

**Comment by adriatic** [comment]
I am using Sublime as Atom seems incredibly slow ( at least on uptake)
