### ISSUE TITLE
Should the file "sample/config.js" be persisted in the repository?

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#192]
I have the habit of always running the jspm update whenever I get some non-trivial files updated via pull. This results with issues like this:
```
@@ -22,7 +22,7 @@ System.config({
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.5",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.6",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.0-beta.1",
    "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
    "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
@@ -41,7 +41,7 @@ System.config({
    "prism": "github:PrismJS/prism@1.3.0",
    "showdown": "github:showdownjs/showdown@1.3.0",
    "github:JeroenVinke/aurelia-prism-plugin@1.0.2": {
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.5",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.6",
      "prism": "github:PrismJS/prism@1.3.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
@@ -70,7 +70,7 @@ System.config({
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.5",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.6",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.0.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.1",
@@ -81,7 +81,7 @@ System.config({
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.0.2",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.0.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.3",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.3",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.4",
...
```

Note that now my aurelia plugins are newer that what they are in the repository before I pulled from GitHub - and I have local changes that prevent me to do the next pull 

#### This should be handled the same way as dist folder as config.js is a generated file

**Comment by charlespockert** [comment]
You should do a `jspm install` rather than an update as otherwise you are
telling our plugin that you want to update any dependencies to their latest
versions.

If you actually do want to do this then the config.js file should get
pushed to the repo, otherwise it won't be affected

**Comment by adriatic** [comment]
I really do not care about the state of the config.js in the repo - as far as I am concerned (assuming that this is the right position) config.js should be recreated each time after a pull so I can know that I am using the latest Aurelia components when developing

**Comment by JeroenVinke** [comment]
> so I can know that I am using the latest Aurelia components when developing

What's the problem with 'old'  versions?

**Comment by adriatic** [comment]
There is no problem with old versions of course and me forcing the issue to always develop using the latest Aurelia components can only harm team efforts, so consider this issue closed (I will not run `jspm update` anymore)

Just to be completely transparent: there are situations where running `jspm install ` (versus jspm update) can result with a serious trouble, because jspm **will not** ensure that the config.js is fully equivalent to package.json -- unlike the case with `jspm update`, where jspm will actually remove entries from config.js which do not exist in package.json any more
