### ISSUE TITLE
All code needs to be a lot better commented

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#196]
I used to like how Angular team does this - even if one can say that they went overboard - ratio of code versus comment is less than 1/10

Perhaps **[this](https://github.com/aurelia/templating/blob/master/src/composition-engine.js)** should be the minimum although I think the comments in this file are written to be able to automatically extract api docs - which is of no interest to us.

In general code comments are written to simplify the life of the next guy

**Comment by JeroenVinke** [comment]
> Perhaps this should be the minimum although I think the comments in this file are written to be able to automatically extract api docs - **which is of no interest to us.**

I disagree. Where else are people going to find information about which functions are available on our wrappers and what parameters to use when calling these function? I have found myself consulting the "extracted api docs" quite often.

Also, the "extracted api docs" are generated from the typescript definition file ([link](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/dist/aurelia-kendoui-plugin.d.ts)), so if we comment the way Aurelia comments, typescript users are able to see these comments right in their editor.

**Comment by adriatic** [comment]
I agree with your disagreement, actually. My original comment was intended to indicate the fact that the "primary programming model" for Kendo is **declarative** and that is not easy to extract from comments.

**Comment by JeroenVinke** [comment]
I agree, which is why we should different kinds of documentation.

- Code as described above (for developers of the plugin, and for users in some use-cases)
- Demo's ( how to use the HTML api we made)
- Articles ( the big picture view, and detailed information about some aspects of our plugin)

**Comment by adriatic** [comment]
:-)

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/e24561288fe0a7d5df1cf50f9da1a63eefd70e78
