### ISSUE TITLE
internal documents needed 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#197]
1. How to create a new wrapper (for example, where the `let options = jQuery.fn[controlName].widget.prototype.options;` gets all options (attributes, I guess). Few days ago, we had to look at http://docs.telerik.com/kendo-ui/api/javascript/ui/treeview and manualy extract them - now, I believe the new way fetches these from KendoUI plugins

2. More to come as needed

**Comment by JeroenVinke** [comment]
I plan to document this in articles

**Comment by adriatic** [comment]
Closing this issue since I is a subset of the issue  https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/174
