### ISSUE TITLE
KendoUI Web Components

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#2]
#### davidpurkiss writes

I think something that should be discussed sooner rather than later is the current support that Telerik provides for web components with KendoUI.

http://docs.telerik.com/kendo-ui/webcomponents

Personally, I've been avoiding the issue as that means I need to now understand, intimately, how web components work. Over the last few weeks as my understanding of Aurelia has grown and having had a chance to play around with building custom elements properly, I feel like this is now less of a task. 

Off the bat, I've come across this [article](http://developer.telerik.com/featured/web-components-ready-production/) and this [aurelia issue](https://github.com/aurelia/framework/issues/7). So it sounds like the Telerik web components are based on Polymer's implementation of custom elements which means we will never be able to use them with Aurelia (unless your bring Polymer into Aurelia, which sounds undesirable), which I don't think is really an issue. At this point I don't know yet, perhaps someone else has some insight?

For me the more important question is, should we be basing our implementation on Telerik's web component implementation. In other words, ideally I would copy and paste some sample from the KendoUI documentation into an Aurelia app and it just works.

I guess the TL:DR of the issue is, how do KendoUI components fit into this project?

**Comment by JeroenVinke** [comment]
I believe that our wrappers are web components also, but are more integrated with aurelia than the web components of Kendo itself. I don't see any reason why we should use their web component controls.
