### ISSUE TITLE
Add bundle revision to demo site

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#201]
https://github.com/aurelia/bundler/blob/master/README.md#example-gulp-task

should help with caching issues

**Comment by adriatic** [comment]
I do not understand what is going on here

**Comment by JeroenVinke** [comment]
Basically when you bundle, it concatenates all files into `app-build.js`. When a browser downloads this file, it caches it. So even when we release a new version, the browser will think: "Ah, I still have app-build.js in my cache, I'll just serve that".

By adding the "rev" property, not `app-build.js` is generated but `app-build-<<unique number>>.js`. That way, when we release a new version it has a different file name, and the browser won't try and serve it from the cache.

**Comment by adriatic** [comment]
Great. I believe that you realize that my insatiable curiosity is driven by my desire to try creating the best documentation for our project.
