### ISSUE TITLE
Use both attribute and custom element

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#203]
`<k-slider></k-slider>`
and
`<input k-slider/>`

Can we use both?

**Comment by JeroenVinke** [comment]
We can, if we decorate the wrapper with both @customElement and @customAttribute :smile:

**Comment by JeroenVinke** [comment]
not recommended, and doesn't work for all controls: https://github.com/aurelia/templating/issues/172#issuecomment-139833093

**Comment by adriatic** [comment]
**What is the origin** of the "perceived need" for that? Vheisse's Render custom element from a custom attribute #172? He comes from a different use case scenario I think/

**Comment by JeroenVinke** [comment]
I have seen that Angular used both `<k-grid>` and `<table k-grid>` .. I wondered if we could do the same

**Comment by adriatic** [comment]
Thanks, I understand it now
