### ISSUE TITLE
refactor samples into their own folder

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#205]
I suggest we create a `samples` folder which would contain all the samples, so that "special" folders such as "help", "installation-wizard" stand out more. We will soon have more and more folders, so we will help our future selfs if we do this sooner than later 

![image](https://cloud.githubusercontent.com/assets/2189477/12004134/9c8b73b8-ab41-11e5-99c4-7e32c8f60750.png)

**Comment by adriatic** [comment]
Cannot agree more as the ease of maintenance trumps any possible performance penalties due to the lengths of the paths used by the router (after all this is really not a real application)

**Comment by adriatic** [comment]
Thank you!
