### ISSUE TITLE
redesign overall navigation model

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#206]
This issue is inspired by @JeroenVinke's  [drawing in gitter - December 24, 2015 2:21 PM](https://gitter.im/adriatic/Aurelia-KendoUI?at=567c45cd4f069158055bc114)

![image](https://cloud.githubusercontent.com/assets/2712405/12004251/b471cea2-ab17-11e5-8930-a94414b6caf6.png)

### Problem definition

No standard menubar (including all variants where menubar items are structured elements) fits our need here - mostly because this application is quite non-standard and we want to offer the user (Aurelia Developer who wants to use KendoUI controls) as unfettered access to the most important information - a "two dimensional matrix" of examples on how to use .KendoUI controls as possible. 

### Proposed solution

Telerik has tried to solve this UI design problem by offering the ["two dimensional" UI](http://demos.telerik.com/kendo-ui/) approach, similar to, but less performant than our `Project status` top level menubar item (which we will keep throughout the development phase)

@JeroenVinke proposes the dynamic hierarchical  collection of buttons organized in rows to offer quick and logical access to control pages. The process starts with the click on the "home page" of the  (currently Bootstrap) menubar where the all top level menu-items are 

![image](https://cloud.githubusercontent.com/assets/2712405/12007345/d7576c2c-abcd-11e5-940c-b512664c2da2.png)

Click on `KendoUI Samples` adds the **[KendoUI toolbar](http://demos.telerik.com/kendo-ui/toolbar/index)**  buttons where button titles are the names of the **main KendoUI control categories**:

![image](https://cloud.githubusercontent.com/assets/2712405/12007471/267e7948-abd4-11e5-9017-4401bb4ca5e5.png)

Now, the problem with this is with click on the button with the title `Charts`  - as click on that button should result with the second row of buttons with names of all Chart "types", where the number of these types (18 at the moment) may exceed the "normal" width of the browser window, even if we remove the word `Charts` from each title

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/12004308/069fe966-ab1d-11e5-95bb-a74f5bf781e2.png"></img>
</p>

`Editors` and `Most popular` buttons also might have more buttons that fit the row.

**Using KendoUI toolbar** addresses this problem completely because it is designed with the "mobile first" approach in mind - as shown **[here](http://demos.telerik.com/kendo-ui/toolbar/resizing)**. Here is the screenshot of the situation when the user clicked on `Chart` button located on **main KendoUI control categories**.

![image](https://cloud.githubusercontent.com/assets/2712405/12007518/39056598-abd6-11e5-8a83-a0a6eff1566f.png)

Clearly, the content of the KendoUI Toolbar located in the second row is a function of which button clicked in the first row.

I propose to add the page to the collection in the **[test](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample/src/test)** folder where we can verify the "look and feel" of such approach, before committing to it.

**Comment by JeroenVinke** [comment]
Menubar is fine by me. We'll still have a "samples"  top level menu item, right?

**Comment by JeroenVinke** [comment]
@adriatic it is merged into master
