### ISSUE TITLE
Plunker - to use or not to use?

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#208]
Each KendoUI demo page has the link to Dojo, allowing the user to experiment with that code section. 

As we already have a pretty good understanding on how to run Aurelia in Plunker, we should at some point consider creating all samples in the Plunker

**Comment by JeroenVinke** [comment]
Should be doable, we can fork [aurelia-plunker](https://github.com/jdanyow/aurelia-plunker) and add our plugin + kendo on top of that configuration. then we can pull from there every time aurelia is updated

**Comment by JeroenVinke** [comment]
repository: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plunker
readme: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plunker/blob/master/README.md
plunker button: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/README.md
plunker link: http://plnkr.co/edit/opehG8?p=preview

**Comment by adriatic** [comment]
Superb response to my proposal - response I did not expect nearly that soon. Thank you Jeroen :-)
