### ISSUE TITLE
Family of Aurelia-KendoUI (AK)  skeleton applications

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#209]
Starting with the obvious choice - AK Skeleton Navigation, ~~we can gradually enter the field of MEAN apps where **A** is replaced by **AK** - all created using **[Aurelia CLI](https://github.com/aurelia/cli)**~~

All of our "kits" should be considered as parts of **[Aurelia Beginner Kits collection](https://github.com/aurelia/beginner-kits)**

**Comment by JeroenVinke** [comment]
Why the MEAN stack? We just want to show the integration between Aurelia and Kendo, I don't see why we need a server component for that.

**Comment by adriatic** [comment]
Because adding KendoUI to Aurelia is the first step in my "strive" to use Aurelia for application development. You are correct in stating "We just want to show the integration between Aurelia and Kendo" however, so my statement "we can gradually enter the field of MEAN apps where **A** is replaced by **AK** - all created using **[Aurelia CLI](https://github.com/aurelia/cli)**" belongs to a different project (the one that brought me here and which one I will resume at some point)
