### ISSUE TITLE
Document bundling

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#217]
Without minification and the [combined scripts](http://docs.telerik.com/kendo-ui/intro/installation/what-you-need#combined-scripts) the Kendo bundle is 6MB (while kendo.all.min.js is 2MB). If you then look into this file, it is tens of thousands of lines long. When you try and minify this bundle, the bundler just gets stuck.

**Comment by adriatic** [comment]
Not good - as I have some doubts in Aurelia bundling, based on so many attempts to make it work. 

How about switching to the simple strategy of using just `kendo.all.min.js` (instead of the more fine resolution approach of using just a specific kendo plugin that is needed in a give app) - as a temporary solution?

The danger here is that having  `kendo.all.min.js` is equivalent to having a PRO license.

**Comment by JeroenVinke** [comment]
> How about switching to the simple strategy of using just kendo.all.min.js (instead of the more fine resolution approach of using just a specific kendo plugin that is needed in a give app) - as a temporary solution?

Not just yet, I want to check this problem out a bit more, and possibly raise issues in aurelia's bundler repository or systemjs-builder.

**Comment by JeroenVinke** [comment]
@adriatic this is what I know now:


# Bundling Kendo
The Aurelia-KendoUI-plugin is designed to offer you - as end-user - flexibility. The wrappers include only the Kendo files they need for that particular control to work. These files exist (in minified state) in the `js` directory of Kendo. 

If you're reading this, then you may be wondering how to bundle these files. There are a currently two options for you to consider, but first let's explain what's in the `js` directory first.

___js directory___

In the `js` folder, there are two kinds of scripts: individual and combined scripts. An individual script is a file such as `kendo.button.min.js`, containing only one "feature". Combined scripts contain multiple "individual" scripts.

Combined scripts are:
- kendo.ui.core.min.js (only in the CORE version of Kendo)
- kendo.all.min.js
- kendo.web.min.js
- kendo.dataviz.min.js
- kendo.mobile.min.js

The Aurelia-KendoUI plugin does not use the __combined__ scripts above, but the __individual__ files such as `kendo.button.min.js`. Thay way, if you only use the button, you would only have to load `kendo.button.min.js` instead of the 2MB `kendo.all.min.js`.

Now that you know this, you can choose one of the following options.

## No bundling at all
This is definitely the easiest option. Instead of bundling the files together, you deploy the entire `js` folder. Only the controls you configure in the `main.js` file of your application will be loaded, in multiple requests. 

To prevent the JSPM bundler from bundling any Kendo files, you can use this bundle configuration:

```
    "dist/app-build": {
      "includes": [
        "*",
        "aurelia-kendoui-plugin",
        "aurelia-kendoui-plugin/**/*",
        "aurelia-kendoui-plugin/**/*.html!text",
      ],
      "excludes": [
        "kendo-ui",
        "kendo-ui/**/*.js"
      ]
    }
```

Note: in the `excludes` property we exclude `kendo-ui` - and all Javascript files within - from the bundle.

## Bundling via JSPM
If you want to bundle Kendo, we recommend you to create a seperate bundle. You will want to bundle the minified files in the `js` folder.

### Core

    "dist/kendo-bundle": {
      "includes": [
        "kendo-ui",
        "kendo-ui/**/*.js"
      ],
      "excludes": [
        "kendo-ui/js/angular.min.js",
        "kendo-ui/js/jquery.min.js",
        "kendo-ui/js/kendo.angular.min.js",
        "kendo-ui/js/kendo.angular2.min.js",
        "kendo-ui/js/kendo.ui.core.min.js"
      ]
    }

Note: We have excluded some files from the bundle, because it's unlikely that these files will be used. We also exclude the __combined__ file `kendo.ui.core.min.js`, because we are creating our own bundle from all the individual files.
    
### PRO
Kendo PRO is quite difficult to get bundled. For example, the bundler chokes when you try to bundle (and minify) all files (kendo.spreadsheet.min.js included). It works fine without minification, but without minification you'll end up with a file of ~7MB.

Since the spreadsheet is not fully ready yet, we want to exclude this from the bundle.

    "dist/kendo-bundle": {
      "includes": [
        // "kendo-ui/js/angular.min.js",
        // "kendo-ui/js/jquery.min.js",
        "kendo-ui/js/jszip.min.js",
        // "kendo-ui/js/kendo.all.min.js",
        // "kendo-ui/js/kendo.angular.min.js",
        // "kendo-ui/js/kendo.angular2.min.js",
        "kendo-ui/js/kendo.aspnetmvc.min.js",
        "kendo-ui/js/kendo.autocomplete.min.js",
        "kendo-ui/js/kendo.binder.min.js",
        "kendo-ui/js/kendo.button.min.js",
        "kendo-ui/js/kendo.calendar.min.js",
        "kendo-ui/js/kendo.color.min.js",
        "kendo-ui/js/kendo.colorpicker.min.js",
        "kendo-ui/js/kendo.columnmenu.min.js",
        "kendo-ui/js/kendo.columnsorter.min.js",
        "kendo-ui/js/kendo.combobox.min.js",
        "kendo-ui/js/kendo.core.min.js",
        "kendo-ui/js/kendo.data.min.js",
        "kendo-ui/js/kendo.data.odata.min.js",
        "kendo-ui/js/kendo.data.signalr.min.js",
        "kendo-ui/js/kendo.data.xml.min.js",
        "kendo-ui/js/kendo.dataviz.barcode.min.js",
        "kendo-ui/js/kendo.dataviz.chart.funnel.min.js",
        "kendo-ui/js/kendo.dataviz.chart.min.js",
        "kendo-ui/js/kendo.dataviz.chart.polar.min.js",
        "kendo-ui/js/kendo.dataviz.core.min.js",
        "kendo-ui/js/kendo.dataviz.diagram.min.js",
        "kendo-ui/js/kendo.dataviz.gauge.min.js",
        "kendo-ui/js/kendo.dataviz.map.min.js",
        // "kendo-ui/js/kendo.dataviz.min.js",
        // "kendo-ui/js/kendo.dataviz.mobile.min.js",
        "kendo-ui/js/kendo.dataviz.qrcode.min.js",
        "kendo-ui/js/kendo.dataviz.sparkline.min.js",
        "kendo-ui/js/kendo.dataviz.stock.min.js",
        "kendo-ui/js/kendo.dataviz.themes.min.js",
        "kendo-ui/js/kendo.dataviz.treemap.min.js",
        "kendo-ui/js/kendo.datepicker.min.js",
        "kendo-ui/js/kendo.datetimepicker.min.js",
        "kendo-ui/js/kendo.dom.min.js",
        "kendo-ui/js/kendo.draganddrop.min.js",
        "kendo-ui/js/kendo.drawing.min.js",
        "kendo-ui/js/kendo.dropdownlist.min.js",
        "kendo-ui/js/kendo.editable.min.js",
        "kendo-ui/js/kendo.editor.min.js",
        "kendo-ui/js/kendo.excel.min.js",
        "kendo-ui/js/kendo.filebrowser.min.js",
        "kendo-ui/js/kendo.filtercell.min.js",
        "kendo-ui/js/kendo.filtermenu.min.js",
        "kendo-ui/js/kendo.fx.min.js",
        "kendo-ui/js/kendo.gantt.list.min.js",
        "kendo-ui/js/kendo.gantt.min.js",
        "kendo-ui/js/kendo.gantt.timeline.min.js",
        "kendo-ui/js/kendo.grid.min.js",
        "kendo-ui/js/kendo.groupable.min.js",
        "kendo-ui/js/kendo.imagebrowser.min.js",
        "kendo-ui/js/kendo.list.min.js",
        "kendo-ui/js/kendo.listview.min.js",
        "kendo-ui/js/kendo.maskedtextbox.min.js",
        "kendo-ui/js/kendo.menu.min.js",
        "kendo-ui/js/kendo.mobile.actionsheet.min.js",
        "kendo-ui/js/kendo.mobile.application.min.js",
        "kendo-ui/js/kendo.mobile.button.min.js",
        "kendo-ui/js/kendo.mobile.buttongroup.min.js",
        "kendo-ui/js/kendo.mobile.collapsible.min.js",
        "kendo-ui/js/kendo.mobile.drawer.min.js",
        "kendo-ui/js/kendo.mobile.listview.min.js",
        "kendo-ui/js/kendo.mobile.loader.min.js",
        // "kendo-ui/js/kendo.mobile.min.js",
        "kendo-ui/js/kendo.mobile.modalview.min.js",
        "kendo-ui/js/kendo.mobile.navbar.min.js",
        "kendo-ui/js/kendo.mobile.pane.min.js",
        "kendo-ui/js/kendo.mobile.popover.min.js",
        "kendo-ui/js/kendo.mobile.scroller.min.js",
        "kendo-ui/js/kendo.mobile.scrollview.min.js",
        "kendo-ui/js/kendo.mobile.shim.min.js",
        "kendo-ui/js/kendo.mobile.splitview.min.js",
        "kendo-ui/js/kendo.mobile.switch.min.js",
        "kendo-ui/js/kendo.mobile.tabstrip.min.js",
        "kendo-ui/js/kendo.mobile.view.min.js",
        "kendo-ui/js/kendo.multiselect.min.js",
        "kendo-ui/js/kendo.notification.min.js",
        "kendo-ui/js/kendo.numerictextbox.min.js",
        "kendo-ui/js/kendo.ooxml.min.js",
        "kendo-ui/js/kendo.pager.min.js",
        "kendo-ui/js/kendo.panelbar.min.js",
        "kendo-ui/js/kendo.pdf.min.js",
        "kendo-ui/js/kendo.pivot.configurator.min.js",
        "kendo-ui/js/kendo.pivot.fieldmenu.min.js",
        "kendo-ui/js/kendo.pivotgrid.min.js",
        "kendo-ui/js/kendo.popup.min.js",
        "kendo-ui/js/kendo.progressbar.min.js",
        "kendo-ui/js/kendo.reorderable.min.js",
        "kendo-ui/js/kendo.resizable.min.js",
        "kendo-ui/js/kendo.responsivepanel.min.js",
        "kendo-ui/js/kendo.router.min.js",
        "kendo-ui/js/kendo.scheduler.agendaview.min.js",
        "kendo-ui/js/kendo.scheduler.dayview.min.js",
        "kendo-ui/js/kendo.scheduler.min.js",
        "kendo-ui/js/kendo.scheduler.monthview.min.js",
        "kendo-ui/js/kendo.scheduler.recurrence.min.js",
        "kendo-ui/js/kendo.scheduler.timelineview.min.js",
        "kendo-ui/js/kendo.scheduler.view.min.js",
        "kendo-ui/js/kendo.selectable.min.js",
        "kendo-ui/js/kendo.slider.min.js",
        "kendo-ui/js/kendo.sortable.min.js",
        "kendo-ui/js/kendo.splitter.min.js",
        // "kendo-ui/js/kendo.spreadsheet.min.js",
        "kendo-ui/js/kendo.tabstrip.min.js",
        "kendo-ui/js/kendo.timepicker.min.js",
        "kendo-ui/js/kendo.timezones.min.js",
        "kendo-ui/js/kendo.toolbar.min.js",
        "kendo-ui/js/kendo.tooltip.min.js",
        "kendo-ui/js/kendo.touch.min.js",
        "kendo-ui/js/kendo.treelist.min.js",
        "kendo-ui/js/kendo.treeview.draganddrop.min.js",
        "kendo-ui/js/kendo.treeview.min.js",
        "kendo-ui/js/kendo.upload.min.js",
        "kendo-ui/js/kendo.userevents.min.js",
        "kendo-ui/js/kendo.validator.min.js",
        "kendo-ui/js/kendo.view.min.js",
        "kendo-ui/js/kendo.virtuallist.min.js",
        // "kendo-ui/js/kendo.web.min.js",
        "kendo-ui/js/kendo.webcomponents.min.js",
        "kendo-ui/js/kendo.window.min.js",
        "kendo-ui/js/pako_deflate.min.js",
      ],
      "options": {
        "inject": true,
        "minify": true,
      }
    }
    
Note, we exclude a couple of files. Some are __combined__ files, some are unnecessary, and we also exclude the spreadsheet because it gets the bundler stuck.


You are probably wondering why we don't just use a glob to include everything we want, and exclude the ones we don't want. Tthis is also causing the issue where the bundler gets stuck. We are not sure why. In theory the exact same should happen as in the configuration above, but it's different somehow. If you figure this out, please let us know so we can update this page. This is the configuration for it:

```
    "src/kendo-bundle": {
      "includes": [
        "kendo-ui/js/*.min.js"
      ],
      "exludes": [
        "kendo-ui/js/angular.min.js",
        "kendo-ui/js/jquery.min.js",
        "kendo-ui/js/kendo.angular.min.js",
        "kendo-ui/js/kendo.angular2.min.js",
        "kendo-ui/js/kendo.spreadsheet.min.js",
        "kendo-ui/js/kendo.all.min.js",
        "kendo-ui/js/kendo.web.min.js",
        "kendo-ui/js/kendo.dataviz.min.js",
        "kendo-ui/js/kendo.dataviz.mobile.min.js",
        "kendo-ui/js/kendo.mobile.min.js"
      ],
      "options": {
        "inject": true,
        "minify": true,
      }
    }
```


### Mapping to kendo.all.min.js
##### Note, this is not recommended and has not been tested fully

In your config.js, you can map Kendo files to `kendo.all.min.js`. If you do this, then you can just deploy `kendo.all.min.js` to your server, instead of bundling all individual files first.

```
    "github:aurelia-ui-toolkits/aurelia-kendoui-plugin@master": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.6",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.0.2",
      "kendo-ui/js/kendo.button.min.js": "kendo-ui/js/kendo.all.min.js",
      "jquery": "github:components/jquery@2.1.4"
    },
```

Note: `"kendo-ui/js/kendo.button.min.js": "kendo-ui/js/kendo.all.min.js",`

You will need to map every file in the Kendo `js` directory to the `kendo.all.min.js` file. We have seen that this is possible, but do not recommend you use this, as it is very verbose. If you know a better way to do this mapping, please contact us and we will update the documentation, so that others can use this information.

**Comment by jhpuro** [comment]
I get the following error
[18:02:03] TypeError: Cannot read property 'forEach' of undefined
    at C:\noscan\git\kaski\Kaski.Web\node_modules\systemjs-builder\lib\trace.js:380:20
    at run (C:\noscan\git\kaski\Kaski.Web\node_modules\core-js\modules\es6.promise.js:104:47)
    at C:\noscan\git\kaski\Kaski.Web\node_modules\core-js\modules\es6.promise.js:115:28
    at flush (C:\noscan\git\kaski\Kaski.Web\node_modules\core-js\modules\$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

Configuration looks like

"dist/aurelia-kendo": {
      "includes": [
        "[aurelia-kendoui-plugin]",
        "[aurelia-kendoui-plugin/**/*]",
        "aurelia-kendoui-plugin/**/*.html!text"
      ],
      "options": {
        "inject": true,
        "minify": true,
        "rev": true
      }
    }

Bundling works if I have only aurelia-kendoui-plugin defined.

Any help appreciated.

**Comment by JeroenVinke** [comment]
@jhpuro can you make sure that you remove old bundled files before trying to bundle  again?

I have also prepared [this repository](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors) to demonstrate bundling so you can compare the config. Also, can you install `aurelia-kendoui-bridge`? we have changed the repository name from `aurelia-kendoui-plugin` to `aurelia-kendoui-bridge` so it aligns with our other repositories. More info is [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/description)

**Comment by jhpuro** [comment]
Thanks for noting the new repository. I updated into aurelia-kendoui-bridge and made sure that the configs are the same, however still get the same error message. Old bundle files were also removed. I tried to update my tooling from npm, but the update command ran into errors. Investigation continues.

**Comment by JeroenVinke** [comment]
@jhpuro feel free to join our [gitter channel](https://gitter.im/adriatic/Aurelia-KendoUI). I can help you debug

**Comment by JeroenVinke** [comment]
@jhpuro make sure you update aurelia-bundler (0.3.1) as when I look at line 380 of `node_modules\systemjs-builder\lib\trace.js` I don't see a `.forEach` statement. `node_modules\systemjs-builder\package.json` should say version 0.15.3

**Comment by jhpuro** [comment]
I updated the bundler into 0.3.1, now the error is as below. To my understanding the path sits within the baseurl, which is wwwroot. I wonder if the baseUrl mentioned here is the one from the [bundler config](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/tasks/bundle.js) or one from the config.js

[15:46:22] 'bundle' errored after 753 ms
[15:46:22] Error tracing npm:aurelia-kendoui-bridge@0.1.0/autocomplete/autocomplete at file:///C:/noscan/git/kaski/Kaski.Web/wwwroot/jspm_packages/npm/aurelia-kendoui-bridge@0.1.0/autocomplete/autocomplete.js
        Error: Unable to calculate canonical name to bundle file:///vendors/js/kendo.autocomplete.min.js. Ensure that this module sits within the baseURL or a wildcard path config.
    at getCanonicalNamePlain (C:\noscan\git\kaski\Kaski.Web\node_modules\systemjs-builder\lib\utils.js:203:13)
    at getCanonicalName (C:\noscan\git\kaski\Kaski.Web\node_modules\systemjs-builder\lib\utils.js:130:19)
    at C:\noscan\git\kaski\Kaski.Web\node_modules\systemjs-builder\lib\trace.js:423:36
    at run (C:\noscan\git\kaski\Kaski.Web\node_modules\karma\node_modules\core-js\modules\es6.promise.js:104:47)
    at C:\noscan\git\kaski\Kaski.Web\node_modules\karma\node_modules\core-js\modules\es6.promise.js:115:28
    at flush (C:\noscan\git\kaski\Kaski.Web\node_modules\karma\node_modules\core-js\modules\$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

**Comment by JeroenVinke** [comment]
OK, I was able to reproduce it. There seems to be a bug here.

Instead of having a mapping of `"kendo-ui": "/vendors"` in the `map` section, add a path mapping in the `paths` section: `"kendo-ui/*": "vendors/*",`

so it looks like this:
```
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo-ui/*": "vendors/*",
    "kendo.*": "vendors/js/kendo.*.js"
  },
```

**Comment by adriatic** [comment]
Was it not Guy recommendation to use `map` section for this mapping?

**Comment by JeroenVinke** [comment]
Yes, I have been able to reproduce it in a very small sample app, and will open up an issue

**Comment by jhpuro** [comment]
Thanks, for finding the solution @JeroenVinke . Will go with this for now.
