### ISSUE TITLE
opt-out of globalResources

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#221]
Let's say we configure our plugin to use Kendo pro:
```
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-kendoui-plugin', (kendo) => kendo.pro());
```

In our `configure` method [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/index.js#L23), we then globalize the resources of all our wrappers. All our wrappers contain an 'import' statement for the files the wrapper depends upon, causing it to load Kendo in its entirety. Note, this is before any view is rendered, and thus before any Kendo control is needed.

If we allow the user to configure the plugin not to use globalResources, then the user can be in charge of deciding when a "wrapper" and therefore the appropriate Kendo files should be loaded. I am not sure, but think this is how it would go:

```
<require from="aurelia-kendo-ui/button"></require>
<button k-button>my button</button>
```

In a large application, you may use all controls of kendo PRO, but may not need them all on initial load of the page. In that case, it would be better to `require` these on demand.

**Comment by JeroenVinke** [comment]
To opt-out of globalResources, you can use `withoutGlobalResources()` in the `main.js`:

```
aurelia.use
  .standardConfiguration()
  .developmentLogging()
  .plugin('aurelia-kendoui-plugin', (kendo) => kendo.pro().withoutGlobalResources());
```


The basic use sample of the grid, without globalResources looks like this:

```
<template>
    <require from="aurelia-kendoui-plugin/grid/grid"></require>
    <require from="aurelia-kendoui-plugin/grid/au-col"></require>

    <k-grid k-data-source.bind="datasource" k-pageable.bind="pageable" k-sortable.bind="true">
      <au-col title="Contact Name" field="ContactName">
        <div class='customer-photo' style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
        <div class='customer-name'>${ContactName}</div>
      </au-col>
      <au-col title="Contact Name" field="ContactName"></au-col>
      <au-col title="Contact Title" field="ContactTitle"></au-col>
      <au-col title="Company Name" field="CompanyName"></au-col>
      <au-col field="Country"></au-col>
    </k-grid>
</template>
```

Note the `<require>` tags

**Comment by JeroenVinke** [comment]
@adriatic are we going to have a page in the docs describing the initialization of our plugin?

for example:

pro:
```
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-kendoui-plugin', (kendo) => kendo.pro());
`` 


pro without global resources:
```
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-kendoui-plugin', (kendo) => kendo.pro().withoutGlobalResources());
`` 

specific controls:
```

pro:
```
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-kendoui-plugin', (kendo) => kendo.button());
``

**Comment by adriatic** [comment]
## YES

I am preparing the documents to be have notes where I need additional information from you and I will send you notifications about all these needs.

In general, until your most recent refactoring of several important areas on the wrapper side, I could have written everything the plugin developers might need without asking for any details. Now, I think that it is a lot more time efficient that I do ask you for information than leaving me to figure it first.
