### ISSUE TITLE
Remove "if" checks for widget in method proxies

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#224]
instead of silently failing, let's remove the [if's](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/chart/chart.js#L65) and show an error when the widget is used uninitialized

**Comment by JeroenVinke** [comment]
Ah, I now know why we have these if's.

```
export class Slider {
  @bindable kValue;

  kValueChanged() {
    this.widget.value(this.kValue);
  }
}

<input k-slider="k-value.bind: 15" />
```

In the above example, the `k-value` binding of the input would update the `kValue` bindable property, causing the `kValueChanged()` function to execute, and then it throws an error because `this.widget` has not been initialized yet.

**Comment by adriatic** [comment]
I actually look forward to now have the opportunity to learn all that you did - as it all has to be documented
