### ISSUE TITLE
Delegate does not work

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#225]
somehow, `.delegate` does not work

this works:
```
      <div id="eventsProgressBar"
           k-progress-bar
           k-on-change.trigger="onChange()"
           k-on-complete.trigger="onComplete()"
           k-progress-bar.ref="pb"></div>
```

this does not:
```
      <div id="eventsProgressBar"
           k-progress-bar
           k-on-change.delegate="onChange()"
           k-on-complete.delegate="onComplete()"
           k-progress-bar.ref="pb"></div>
```

**Comment by adriatic** [comment]
Isn't this a problem report for KendoUI? If so, there is little chance that we will get that fixed soon, so we need to use the `trigger` variant. Is this variant in any way different from `delegate`?

**Comment by JeroenVinke** [comment]
No, I think this is our problem.

http://stackoverflow.com/a/33909191/3922366

**Comment by adriatic** [comment]
You threw me off by using the form 'k-on-change` prefix (led me to believe that this is the definition of the Kendo event handler)

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/templating-binding/issues/76

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/ce98d976f013b835f1374270d61fba00eadcfedb
