### ISSUE TITLE
Finish the few chart controls for the release

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#226]
I do not recall what all have the "interactive" behavior (funnel basic, labels and remote data, pie labels I know that they are), so please finish these and check of any other has such issues.

My excuse for heaping this on you is still the same - docs as I want to write enough to get both KendoUI users (app developers) and KendoUI contributors (wrapper developers) fully enabled.

**Comment by JeroenVinke** [comment]
- [ ] http://localhost:3000/#/samples/bar-charts/gap-and-spacing
- [ ] http://localhost:3000/#/samples/funnel-charts/
- [ ] http://localhost:3000/#/samples/pie-charts/pie-labels
