### ISSUE TITLE
Implement Grid's custom editor sample

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#227]
http://localhost:3000/#/samples/grid/editing-custom-editor

**Comment by JeroenVinke** [comment]
I've just hit this issue: :point_up: [December 29, 2015 9:53 PM](https://gitter.im/Aurelia/Discuss?at=5682f2b83c68940269253ef3)

**Comment by JeroenVinke** [comment]
if this is not possible now, and won't be, I have a workaround up my sleeve

**Comment by adriatic** [comment]
Hmmm ... This case is in no way exceptional and should be encountered again. How come that this is a problem in Aurelia (read: I am curious to see what the response to this will be)

**Comment by JeroenVinke** [comment]
@stoffeastrom told me that it's possible with `.bind`:

```
    <k-grid k-pageable.bind="true" k-height.bind="500" k-toolbar.bind="['create']" k-editable.bind="true" k-data-source.bind="dataSource">
      <au-col field="ProductName" title="Product Name"></au-col>
      <au-col field="Category" title="Category" width="180px" editor.bind="categoryDropDownEditor" template.bind="categoryTemplate"></au-col>
      <au-col field="UnitPrice" title="Unit Price" format="{0:c}" width="130px"></au-col>
      <au-col command="destroy" title=" " width="150px"></au-col>
    </k-grid>
```

note the `editor.bind` and the function without parentheses
