### ISSUE TITLE
Funnel charts got squished

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#229]
This does look funny - ;left one in particular :-)

![image](https://cloud.githubusercontent.com/assets/2712405/12041948/280d34bc-ae44-11e5-98e6-2e4491760b8f.png)

**Comment by JeroenVinke** [comment]
let's remove the margin/padding around the sample, do you have this with all funnel charts?

**Comment by adriatic** [comment]
I believe that the solution is in **not showing** legends as that is how the original is rendered:

![image](https://cloud.githubusercontent.com/assets/2712405/12042621/bc5edf5c-ae4a-11e5-9427-757d47cbd202.png)

**Comment by JeroenVinke** [comment]
@adriatic can you try it again with [this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/50d835010cb57575306b05a5a274d26dfb1eaa98) change?

**Comment by adriatic** [comment]
![image](https://cloud.githubusercontent.com/assets/2712405/12043059/fe3dbec6-ae4e-11e5-9aa4-f82227f635d8.png)

**Comment by JeroenVinke** [comment]
much better!
