### ISSUE TITLE
Progress bar "hampered" by hover event

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#230]
Again the picture suffices to explain the problem - but to be safe, when you get the cursor close enough to the "popdown" control trying to select an item, the "down triangle" icon gets hidden:

![image](https://cloud.githubusercontent.com/assets/2712405/12042270/32e13e4e-ae47-11e5-92c3-5ab0466a6667.png)

**Comment by JeroenVinke** [comment]
Right, so in addition to the theme itself, we have to load the additional "common" file

for example, `kendo.material.min.css` needs to be loaded together with `kendo.common-material.min.css`. Currently we're using `kendo.common.min.css` which is the generic version, which works pretty well, if you don't count this issue ;)

![image](https://cloud.githubusercontent.com/assets/2189477/12043319/71f108ac-ae84-11e5-9bc9-12d621650bf1.png)

however, by changing the common file every time, the sample app gets pretty messed up as some parts have static heights, and the common file doesn't take this into account:

![image](https://cloud.githubusercontent.com/assets/2189477/12043357/e7374266-ae84-11e5-9b56-566e73ec756d.png)

I have pushed this change to the `common-theme` branch anyway, so you can take a look

**Comment by adriatic** [comment]
Unlike the case with http://aurelia-ui-toolkits.github.io/demo-kendo I would not discuss the `theme-manager` in our docs.

If everyone (and that means hundreds of users) scream bloody murder requesting this feature -- we will add it later. Let's pick the default theme (probably materialize) and that is what will be in the https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo repo that I created with the intent to have the code used in help docs (the application developer side, that is - not wrapper developer)

**Comment by JeroenVinke** [comment]
So what are you suggesting?

**Comment by adriatic** [comment]
Sorry - `this feature` is a reference to `theme-manager` and **I am suggesting not to surface it** in any initial help docs, since this is really a feature for app developers that we cannot "ship" in the plugin.

I do not believe that you see it any differently.

**Comment by JeroenVinke** [comment]
I agree with you on that point, not many apps will need to switch between themes. But what do you think we should do with https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/230#issuecomment-167893265? If we, in addition to switching themes, also switch between common files, then our sample gets messed up. If we don't, we have the issue you mentioned: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/230#issue-124268972

**Comment by adriatic** [comment]
haven't had the time to process this fully (I do not yet understand the influence of the `common files` in the process of switching themes). I do know that the correct themes switching is possible - as the KendoUI demo app does it without getting messed up.
