### ISSUE TITLE
Need to escape the `>` character (part of the "fat arrow")

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#233]
The line 
```
  aurelia.start().then(a => a.setRoot());
```
is rendered as
```
aurelia.start().then(a =&gt; a.setRoot());
```
in all three installation .md files

**Note**: this is not needed when rendered by our <au-markdown> custom element

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/9baa77fcec7bdb7c318e8274224b736fa9820f68
