### ISSUE TITLE
Scroll position is carried between different views in the help docs

### ISSUE THREAD

**Issue by rocknet** [aurelia-ui-toolkits/aurelia-kendoui-plugin#237]
Environment: Windows 7, Chrome 47.0.2526.106

STR:
1. Navigated to http://aurelia-ui-toolkits.github.io/demo-kendo/#/help
2. Expand About this application
3. Click Internal structure menu item
4. Scroll down to the middle of that page or lower
5. Click How to use this application menu item

Expected: Scoll position goes to the top of the How to use this application page
Actual: Scroll position is lower on the page, apparently using the same relative scroll position as the other view.

**Comment by adriatic** [comment]
Thanks - this is a bug from the viewpoint of the hep system design (while the help system is not yet finished, meaning that you may find many other issues). 

My own preference in situations like this is to maintain the cursor position per tab; that way one can compare something by switching tabs, without having to deal with searching the place where you were before the switch.

**Comment by JeroenVinke** [comment]
Thanks :) Feel free to make changes to the plugin/sample app yourself and to create pull requests.
