### ISSUE TITLE
Ensure that the "wizard like links" in the tutorials use "production" URL

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#243]
Example: the autocomplete.md file points to the development enviroinment (http://localhost:3000)
```
<br>
#### More details: [Components catalog](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/autocomplete)
#### Next page: &nbsp;&nbsp; [Button component tutorial](http://localhost:3000/#/help/docs/app_developers_tutorials/4._button_component)
```

**Comment by JeroenVinke** [comment]
If you do this: 

`#### Next page: &nbsp;&nbsp; [Button component tutorial](#/help/docs/app_developers_tutorials/4._button_component)` then it should work in both dev and production

**Comment by adriatic** [comment]
WOW what entity handles this? 

Great time to tell me this as the Bridge developers tutorials require many such links.
