### ISSUE TITLE
Fix vendors installation instruction

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#250]
` jspm install kendo-ui aurelia-kendoui-plugin` should be ` jspm install aurelia-kendoui-plugin`

**Comment by adriatic** [comment]
Wow - how come that we did not catch that ourselves? It literally means that just reading the documentation (for the purpose of verifying its correctness is not enough)

**Comment by JeroenVinke** [comment]
> Wow - how come that we did not catch that ourselves? It literally means that just reading the documentation (for the purpose of verifying its correctness is not enough)

Yeah, it slipped right through, weird that we didn't hit it ourselves

> Was this something that "harmed" @souldrinker?

Initially yes, but should not cause not the current issue
