### ISSUE TITLE
grid custom editor sample showing [object Object]

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-plugin#251]
The [grid custom editor sample](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/editing-custom-editor) is not showing the value of ```CategoryName``` in the categories column (as I suppose it should).
Instead, it shows ```[object Object]```.

Editing a cell works, though.

**Comment by adriatic** [comment]
Happy to see that @Thanood did actually go through KendoUI Bridge Catalog app - and even more that he did it completely awaken :-)
