### ISSUE TITLE
ignoring "dev" build folder

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-plugin#257]
At the moment we have a `dist` folder which is where the kendo sample application picks its plugin files up from.

This `dist` folder will also be used as the source for transpiled files when the plugin is released.

This causes the issue that building the plugin application during dev changes files in the `dist` folder causing them to be detected as changes by git. These file changes are not important to the plugin source (and may look a little different depending on which machine they were built on - whitespace issues/build tools versions etc), since a dev will re-build them each time they run the project they can safely be ignored.

However, since they have already been added to git at the start of the project, the files are tracked, and since we actually need them on release we can't really gitignore them.

*Proposal*
As suggested by @JeroenVinke, we will split the build into a dev and a release gulp command.

This will build the distribution files into a gitignored dev directory in the plugin root. 

The standard sample gulp pipeline should make use of the dev build process with a new command `build-release` to build into the `dist` folder

**Comment by adriatic** [comment]
Great description of the issue at hand - makes me very happy to have **[initiated it](https://gitter.im/adriatic/Aurelia-KendoUI?at=569c11a9c391361d48eba47a)**.

@charlespockert would you please fix the `build` folder accordingly for all affected repos?
