### ISSUE TITLE
Vendors approach failing with the latest Kendo release 

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#259]
The vendors approach is causing 404's when it is used with the latest Kendo release (2016.1.112). This is due to a breaking change with the paths of file dependencies.

Telerik support ticket:

>  We just noticed that there was a breaking change in the latest Kendo version (2016.1.112) when using Kendo through JSPM/SystemJS. We are getting 404 requests for files such as "kendo.core.min.js" when loading "kendo.button.min.js" or any other Kendo control. We compared the minified Kendo files and saw that the dependency path was changed in the last version:

>  // working in older version
define(["./kendo.core.min"],e)}

>  // failing in the latest
define("kendo.button.min",["kendo.core.min"],e)}

>  Note the missing "./" in the latest version.

>  This change is causing SystemJS to look for "kendo.core.min.js" in the root of the application, not in the same directory as "kendo.button.min.js" and thus causing a 404.

>  If we change this back to a relative path:

>  define("kendo.button.min",["./kendo.core.min"],e)}

>  it is looking for kendo.core.min in the correct location. 

>  However, kendo.core.min.js was also changed in the latest version:

>  // working (old version)
define([],e)

>  // not working (new version, 404 for jquery.min.js)
define("kendo.core.min",["jquery.min"],e)

>  // when adding ./ it finds the jquery.min.js but gives an error 
define("kendo.core.min",["./jquery.min"],e)

>  This is the error when it tries to load jQuery:
Error: AMD module http://localhost:8080/vendors/js/jquery.min.js did not define

>  I have created a repository so that you can test this easily (https://github.com/JeroenVinke/kendo-systemjs-bug).

>  Installation steps:

>  1. npm install
2. jspm install
3. put the "js" folder of the latest Kendo release inside the "vendors" folder
4.  npm install http-server -g
5. http-server
6. go to http://localhost:8080 and look for 404s

>  If you put an older version of Kendo (such as v2015.3.1201) in the vendors folder then it will work correctly

**Comment by JeroenVinke** [comment]
updated the plugin and https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors to kendo 2016. Seems to work.

**Comment by adriatic** [comment]
> updated the plugin and https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors to kendo 2016. 

I am assuming that the whole `vendors` folder is here for the convenience of the Aurelia-KendoUI team - and even then this might upset Telerik more than we would like, since they would see it as illegal distribution of their $1000 product

**Comment by JeroenVinke** [comment]
- We are only uploading the minified and mangled files, which are in no way reversable to the original source files
- These minified and mangled files are in the "dist" folder, the one anyone needs to upload to their server in full for their application to work. kendo.all.min.js is just a concatenation of all the individual files we upload, so there is no difference there. My point here is: there are loads of websites where you can download this from, no secret there.
- if you don't get it from our repository, you can get it from one of the other 10.000 repositories on Github: https://github.com/search?q=kendo.calendar.min.js&type=Code&utf8=%E2%9C%93

**Comment by adriatic** [comment]
> We are only uploading the minified and mangled files, which are in no way reversable to the original source files

Wonderful - not am I only playing the master of the obvious, but rather the **dumb** master of the obvious :-)
