### ISSUE TITLE
Implement Grid

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#40]
- [x] the `_initialize` function is called from bind (only when there are issues, `attached()` may be used)
- [x] bindable properties are sorted alphabetically
- [x] there is a `recreate` function
- [x] Available API methods are proxied in the wrapper (such as `enable`)
- [x] All samples found on Telerik's website are recreated using our wrapper ([example](http://demos.telerik.com/kendo-ui/grid/index))
- [x] changed events of bindable properties are handled, only if there is an API method available. For example, the `kEnable` property of the button has an API function (`enable()`), so the `kEnableChanged()` function should call the `enable()` API function

**Comment by JeroenVinke** [comment]
- [ ] the `_initialize` function is called from bind (only when there are issues, `attached()` may be used)
- [ ] bindable properties are sorted alphabetically
- [ ] there is a `recreate` function
- [ ] there is a `_initialize` function
- [ ] Kendo's options are pruned via the getOptions() function
- [ ] Events are proxied via `fireKendoEvent` (such as `dataBound`)
- [ ] Available API methods are proxied in the wrapper (such as `enable`)
- [ ] The widget is destroyed in the `detached` lifecycle callback
- [ ] The widget is stored in the `widget` property of the wrapper
- [ ] Default values (found in Kendo's docs) of all bindable properties are set
- [ ] All samples found on Telerik's website are recreated using our wrapper ([example](http://demos.telerik.com/kendo-ui/grid/index))
- [ ] changed events of bindable properties are handle, only if there is an API method available. For example, the `enable` property of the button has an API function (`enable()`), so the `enableChanged()` function should call the `enable()` API function
- [ ] if the control supports templating, the [template-compiler](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/common/template-compiler.js) is initialized from `bind()`

**Comment by adriatic** [comment]
Good stuff!
