### ISSUE TITLE
Syntax for @bindables

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-plugin#5]
The development guide specifies that conventions should be avoided if possible as Aurelia allows customisation of these conventions.

Any plugin making an assumption about conventions can fail when those conventions are changed

Does this apply to `@bindables`? I don't think it does - I prefer the convention based approach as it keeps the `@bindable` near the property description:

```
export class MyClass {
    @bindable myProperty;
}
```

It's also possible to decorate the class

```
@bindable({ name: 'myProperty' })
export class MyClass {
}
```

Which is preferred? Do we need to be consistent?

**Comment by adriatic** [comment]
> Does this apply to @bindables? I don't think it does - I prefer the convention based approach as it keeps the @bindable near the property description:

I agree with Charles on using the convention based approach for bindables.

In addition, I prefer this varient:
```javascript
@bindable({ name: 'myProperty' })
export class MyClass {
}
```
Because the bindable property is easier to spot

**Comment by JeroenVinke** [comment]
We settled for this syntax:

```
export class MyClass {
    @bindable myProperty;
}
```
