### ISSUE TITLE
Define and implement the Github based website that shows all controls

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#62]
I created this **[repository](https://github.com/aurelia-ui-toolkits/github.io)** to host files needed to show the current status of developing the three plugins, in the form of a Github-Pages site. This will be initially a bit cooler version of the [site embedded](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample) in [KendoUI plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin), which will subsequently be augmented to also show the the controls from [boostrap plugin](https://github.com/aurelia-ui-toolkits/aurelia-wbootstrap-plugin) and [materialize plugin](https://github.com/aurelia-ui-toolkits/aurelia-materialize-plugin).

**Comment by JeroenVinke** [comment]
this has been implemented
