### ISSUE TITLE
Case of a "missing" hljs object

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#64]
Where is the `hljs` appearing on [this line](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/shared/markdown.js#L24) defined?

This class (`markdown.js`) works just fine in [this plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin) but fails in the [demo app](https://github.com/aurelia-ui-toolkits/demo) which consumes this plugin.

**Comment by adriatic** [comment]
It is possible that I am encountering the problems related to demo app being at beta1 version of Aurelia, while the plugin is older. So, I will rebuild the plugin using the Aurelia beta bits

**Comment by charlespockert** [comment]
FYI I've pushed this branch:

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/kendo-repo

This includes a kendo install from a `kendo` endpoint

Here are install instructions for that endpoint:

```
npm install jspm-git --save-dev
jspm registry create kendo jspm-git
```
When it asks you for the repo root enter:
```
https://bower.telerik.com/
```
Then use
```
jspm install kendo-ui:bower-kendo-ui
```

**Comment by adriatic** [comment]
Either are you too terse or I am too dense - either way it is not clear whether (after the pull of "kendo-repo" branch) I should first do
```
npm install
cd sample
jspm install
```
and then the newly added commands
```
npm install jspm-git --save-dev
jspm registry create kendo jspm-git
```

**or**

just the second set.

**Comment by charlespockert** [comment]
Ah, this comes from the chore of having to maintain two projects at once!

The package.json for the sample project needs updating (not sure why it works on mine and it hasn't updated the package.json...)

**Comment by charlespockert** [comment]
@adriatic FYI this is fixed, the package should work correctly now, I've cloned it into an empty repo etc

You need to make sure your kendo endpoint is registered before you run `jspm install`
