### ISSUE TITLE
Implement defaults for config callback

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-plugin#66]
Should include core/pro defaults which include all core and all pro controls.

We will have to iterate this as we implement each control wrapper

**Comment by charlespockert** [comment]
Leaving this one open as I'd like to make all the config callbacks methods rather than strings - this will help people using code-hinting tools

**Comment by adriatic** [comment]
Great idea

**Comment by charlespockert** [comment]
OK closing as it's been done [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/0afb4dd25c035083052f4600e47d343442a07fc5)
