### ISSUE TITLE
Need to generate d.ts files

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-plugin#67]
Type info is a requirement as it will help define the API for the plugin and the controls for users consuming the definitions

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/tools/issues/24

**Comment by JeroenVinke** [comment]
I have implemented a workaround for the issue above, but hit another issue: https://github.com/aurelia/framework/issues/255. I don't know how to fix or workaround this, so dts generation is on hold for a while I think

**Comment by JeroenVinke** [comment]
this is now in master
