### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by charlespockert** [aurelia-ui-toolkits/aurelia-kendoui-plugin#69]
We need to dev using the pro version of Kendo, but upon release the core version should be the default bundle

This could be a release build step, but basically we need to ensure `config.js` and `package.json` are updated to reflect Core rather than Pro libs.

What's the best approach here? Any suggestions?

**Comment by JeroenVinke** [comment]
can't we just keep kendo-core in the config.js of the plugin, and override it in the sample app?

**Comment by charlespockert** [comment]
:headdesk: yes we can...
