### ISSUE TITLE
Create a sample app with the jspm-git approach

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#77]
It could even be a skeleton-navigation clone

**Comment by adriatic** [comment]
I believe (but am not sure) that if you define the "bower based endpoint" in the package.json, then `jspm` will add the reference to `jspm-git` to the (jspm generated) config.js file

This nearly killed me trying to get rid of references to jspm-git - only when I replaced the intent to use bower based Kendo distribution with GitHub KendoUI-core, I got rid of jspm-got

**Comment by JeroenVinke** [comment]
So, I have just confirmed that with the current setup (having kendo-core as dep in the plugin's package.json), you have to override this dependency when installing the plugin.

Turns out it's easier to do this by using `map` than overriding `dependencies`, because if you override `dependencies` you have to list repeat all dependencies of the plugin and then change one (kendo-ui). if you override `map` then you only need to specify the dependency you wish to override.

`jspm install github:aurelia-ui-toolkits/aurelia-kendoui-plugin -o "{ map: { 'kendo-ui': 'kendo:bower-kendo-ui@2015.2.813' } }"`

**Comment by adriatic** [comment]
I am assuming that 'kendo:bower-kendo-ui@2015.2.813' is a reference to the PRO version?

It's really good that you are pushing the "smooth" KendoUI PRO plugin installation as this is really where it matters the most.

**Comment by JeroenVinke** [comment]
You are correct in assuming that it is the PRO version of kendo. This was installed by running `jspm install kendo-ui=kendo:bower-kendo-ui` after installing  `jspm-git` and registering the `kendo` endpoint with jspm

Perhaps we can remove the version number from the override :open_mouth:

**Comment by JeroenVinke** [comment]
The sample repository can be found [here](https://github.com/JeroenVinke/aurelia-kendoui-jspm-git). The README contains some clues on how to get the app running and how the steps it took to include our plugin (using jspm-git) in a new skeleton-navigation app

**Comment by adriatic** [comment]
Like the [README.md](https://github.com/JeroenVinke/aurelia-kendoui-jspm-git/blob/master/README.md) a lot!

**Comment by JeroenVinke** [comment]
I have moved the sample app [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-jspm-git)
