### ISSUE TITLE
Improve kendo-PRO installation process

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#78]
We should support two ways of installing kendo PRO:
- via bower (using the jspm-git plugin)
- via a vendors folder (as used today in the sample app)

The sample apps uses the vendors folder approach right now so that we can atleast get the plugin running and develop wrappers. In parallel we can take another stab at the jspm-git approach and perhaps fix issues we encounter.

Todo for jspm-git approach:
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/76, https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/77, https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/87

Todo for vendors approach:
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/75

**Comment by JeroenVinke** [comment]
I wonder if we can configure credentials for jspm-git so headless build servers can also run `jspm install` without getting stuck on the credentials prompt

**Comment by adriatic** [comment]
This is certainly possible as I saw KendoUI PRO installation process description (somewhere in Kendo help pages) that show several methods for "hiding" the credentials in a platform independent way for precisely same reason you brought up

**Comment by JeroenVinke** [comment]
@adriatic I think we can close this issue. we have 3 ways of installing kendo (basic, jspm-git and vendors approach), and have documented the installation steps and have samples repositories for all mentioned approaches

**Comment by adriatic** [comment]
Indeed - this turned out a lot better than I expected, mostly due to @JeroenVinke :-)
