### ISSUE TITLE
Create gh-pages

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#82]

**Comment by adriatic** [comment]
I propose to use the **[Project Pages](https://help.github.com/articles/user-organization-and-project-pages/#project-pages)** which means:

Create a separate *project site* for each repository within the organization, by including the site content in the gh-pages branch of the existing repository. That will publish each project site at http://aurelia-ui-toolkits.github.io/<repository-name>.

**Comment by adriatic** [comment]
Web site `demo-kendo` created at http://aurelia-ui-toolkits.github.io/demo-kendo/

**Comment by JeroenVinke** [comment]
@adriatic just to confirm, are you proposing to create the demo site in the master branch of, for example, https://github.com/aurelia-ui-toolkits/demo-bootstrap? and then use the gh-branch to explicitly publish a new version of the demo site? if so, I like it :)

**Comment by JeroenVinke** [comment]
This has been completed: http://aurelia-ui-toolkits.github.io/demo-kendo
