### ISSUE TITLE
Sample page layout change proposal

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#83]
The current sample page is "too influenced" by Aurelia's Navigation Skeleton and does not fit our intent - as in order to "list" all KendoUI controls on the main menu we would need to implement the menubar as a sequence of Kendo controls **categories** (Data Management, Charts, Bar code, Editors, Gauges ...) rendered as DropDownLists, with items being the names of the controls in each category.

Alternatively we can invert the current rendering - replace the positions of the menu bar and side bar. In order to prevent the new side bar to be too tall, we can again make it as an accordion (despite the fact that KendoUI does not have that control), where the primary accordion elements are the KendoUI control categories

**Comment by adriatic** [comment]
Adding a comment to verify the integration with the related [Gitter chat room](https://gitter.im/aurelia-ui-toolkits)

**Comment by JeroenVinke** [comment]
I like the first option you mentioned more than the second option. Adding controls to categories seems like a good idea.

**Comment by adriatic** [comment]
Next issue in this context: At the moment our sample app uses Aurelia defined subset of Bootstrap menubar. For consistency sake, we should replace it with Kendo Toolbar, looking like this

![image](https://cloud.githubusercontent.com/assets/2712405/11443884/e4666d00-94ee-11e5-9453-696455ab2772.png) 

where all toolbar items are KendoUI control categories dropdown lists.

**Comment by JeroenVinke** [comment]
That seems like a good idea. Since we do not have a wrapper for the kendo menubar yet, it will also serve as a good test case for when we start working on the wrapper.

**Comment by adriatic** [comment]
Good you mentioned that - as it might be even simpler to start with the Kendo Menubar wrapper and not even go to the Toolbar (in the Demo app that is, Demo being the app running on Github-pages), since Tool bar and Menu bar are nearly the same thing:

![image](https://cloud.githubusercontent.com/assets/2712405/11444238/ebfa9a48-94f1-11e5-972e-24bf4bee3c85.png)

Screen shot taken from http://demos.telerik.com/kendo-ui/menu/index

So, I am proposing the Aureliazing Kendu Menu first and use it right away In the Demo app.

**Comment by adriatic** [comment]
superseded by https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/206
