### ISSUE TITLE
register plugin in jspm registry

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#84]

**Comment by adriatic** [comment]
Why is this necessary given the existence of the following code in "sample level" `index.html`?

```
<script>
      System.import('aurelia-bootstrapper');

      // Load the package.json from the root to get the package name
      System.import("root/package.json!").then(function(m) {
        var cfg = {
           packages: {}
        };

        // Create a new systemjs package with the package name
        cfg.packages[m.name] = {
            "main": "index",
            "dependencies": m.jspm.dependencies
        };

        System.config(cfg);

      });
```

**Comment by JeroenVinke** [comment]
This would allow our users to install the plugin using `jspm install auerlia-kendui` vs `jspm install github:aurelia-ui-toolkits/aurelia-kendoui-plugin``

**Comment by adriatic** [comment]
Yes, I would always prefer the simpler path - jspm registry is the way.

**Comment by adriatic** [comment]
Note that this change requires the correction in the README.md file

```
1. Install the plugin

  `jspm install github:aurelia-ui-toolkits/aurelia-kendoui-plugin`
```

**Comment by JeroenVinke** [comment]
A good example on how to do this is: https://github.com/zewa666/registry/commit/a5315e43db62c7999615987db5d3dabd2561586a

@adriatic @charlespockert should I go ahead and create a pull request to the registry for `aurelia-kendoui-plugin` ?

**Comment by adriatic** [comment]
I am strongly in favor of doing that rather sooner than later, so that all subsequent development uses that registry allowing us more opportunities to fix any glitches.

**Comment by adriatic** [comment]
That darn close and comment button is simply too close to the comment button :-1:

**Comment by JeroenVinke** [comment]
https://github.com/jspm/registry/pull/676

**Comment by JeroenVinke** [comment]
Done!
