### ISSUE TITLE
kendo images not loading 

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#88]
if you use this code to load kendo's css:

```
  <require from="kendo-ui/styles/kendo.common.core.min.css"></require>
  <require from="kendo-ui/styles/kendo.bootstrap.min.css"></require>
```

you get a 404 for `GET http://localhost:9000/Bootstrap/loading.gif 404 (Not Found)`

the path should be `http://localhost:9000/jspm_packages\github\kendo-labs\bower-kendo-ui@2015.2.813\Bootstrap\loading.gif`

this issue can be replicated by installing [the kendo-core sample app](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-core)

**Comment by adriatic** [comment]
Yep, that is important bug to resolve - as it renders the controls incorrectly:

![image](https://cloud.githubusercontent.com/assets/2712405/11459163/2648b0b0-969e-11e5-82a5-727c671599a5.png)

**Comment by JeroenVinke** [comment]
I also noticed this in the sample app.

The fix was to add an exclamation mark in the `<require>`:

```
<require from="kendo-ui/styles/kendo.common.core.min.css!"></require>
<require from="kendo-ui/styles/kendo.bootstrap.min.css!"></require>
```

**Comment by adriatic** [comment]
### OK, that's it

Now, I will finally learn what is the role if this exclamation mark in this context. Please explain

**Comment by JeroenVinke** [comment]
I think that the exclamation mark signals to systemjs (the module loader) to use a plugin to load the requested file. You could also add `!json` for example, and have a plugin that takes care of loading all `json` files. 

I believe that by adding the exclamation mark, it triggered [systemjs/plugin-css]([systemjs/plugin-css](https://github.com/systemjs/plugin-css)) to load the css file, instead of loading it directly (without the plugin). this is making me think that plugin-css is doing some sort of path translation.

I think that `plugin-css` when asked to serve the css file, modified the paths inside the css file. that way the images are loaded from the correct path.

**Comment by adriatic** [comment]
So, would it not be a better practice to specifically include the `plugin-css` module in package.json than relying of that semantically non-intuitive '!' syntax?

**Comment by JeroenVinke** [comment]
You need both
Op 31 dec. 2015 19:23 schreef "Nikolaj Ivancic" <notifications@github.com>:

**Comment by charlespockert** [comment]
FYI the file extension is used to determine the plugin unless you provide
the plugin name after the !

**Comment by JeroenVinke** [comment]
:o
Op 31 dec. 2015 19:48 schreef "Charles Pockert" <notifications@github.com>:

> FYI the file extension is used to determine the plugin unless you provide
> the plugin name after the !

**Comment by adriatic** [comment]
Based on the distance in time between now and https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/88#issuecomment-161024537 - we have established some assessment of my memory retention.
