### ISSUE TITLE
Improve documentation on how to install and use aurelia-kendoui-plugin

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#89]
I have made 3 different repositories to demonstrate the installation process of the 3 installation options ([core](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-core), [vendors](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors), and [jspm-git](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-jspm-git))

I suggest that we test all these steps and combine these into the [readme of the plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/README.md).

**Comment by JeroenVinke** [comment]
we could even build an installation wizard in the demo site

in this wizard you could say, for example, that you have kendo PRO files but don't have telerik credentials, which will suggest you use the vendor approach to install the plugin.

**Comment by adriatic** [comment]
> we could even build an installation wizard in the demo site

This is the way to do this yes - our web site (_residing in the gh-pages branch of the repository that we use to build the site_) should be the only place anyone visits to either verify the function or to get the chosen installation type. **Full service!**

**Comment by adriatic** [comment]
All three sample apps
1.  [aurelia-kendoui-core](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-core)
2.  [aurelia-kendoui-vendors](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors)
3.  [aurelia-kendoui-jspm-git](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-jspm-git)

function **correctly** as stated in

1.https://github.com/aurelia-ui-toolkits/aurelia-kendoui-core/issues/2
2.https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors/issues/3
3. https://github.com/aurelia-ui-toolkits/aurelia-kendoui-jspm-git/issues/1 

respectively.
