### ISSUE TITLE
Extracting the sample code from the aurelia-kendoui-plugin repository

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#90]
This may be a redundant issue as I have not yet tested the code in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/89, but in order not to lose my train of thoughts from this morning:

@JeroenVinke verified the correct function of jspm-git by modifying the copy of **[skeleton-navigation](https://github.com/aurelia/skeleton-navigation)** to provide three  alternatives:

1. **[aurelia-kendoui-core](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-core)**: Delivers the free KendoUI-Core plugin
1. **[aurelia-kendoui-vendors](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-vendors)**: Delivers the KendoUI-PRO plugin by allowing the customer to "bring" KendoUI toolkit through a private channel
1. **[aurelia-kendoui-jspm-git](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-jspm-git)**: Delivers the KendoUI-PRO plugin by fetching the KendoUI PRO code automatically.

The next obvious step is to to use the **[sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample)** code in lieu of the **[skeleton-navigation](https://github.com/aurelia/skeleton-navigation)** as the "model" to verify the three packaging approaches listed above.

**Note**: I have done this same thing (without the benefit of today's [improvements](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/3f9a9400f2b58067f1fab217dc4f509cb3ba9172) in the [README.md](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/README.md) file) - **each time with slightly different tweaks needed to make it work**. 

Some of the issues include the decision whether use ES6 `import` statements like **[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/app.js#L2-4)** or Aurelia's own `<require>` custom element 
```html
    <require from="bootstrap/css/bootstrap.css"></require>
    <require from="kendo-labs/styles/kendo.common.core.min.css"></require>
    <require from="kendo-labs/styles/kendo.bootstrap.min.css"></require>
```
So, I would really appreciate if @JeroenVinke does this extraction of the **[sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample)** in the three different formats

**Comment by adriatic** [comment]
After discussing it in [this chat-room](https://gitter.im/JeroenVinke) the task is slightly morphed to avoid the unnecessary creation of the **three repos** by doing the extraction of the **[sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample)** in the **three different formats**

**Comment by JeroenVinke** [comment]
This has been completed: http://aurelia-ui-toolkits.github.io/demo-kendo
