### ISSUE TITLE
Update the README.md file in this repository

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#93]
The reference **this** points to https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/README.md

**Comment by JeroenVinke** [comment]
Do you plan to include installation instructions in the readme, or will you just point to the demo site,  where users can follow an installation wizard?

**Comment by adriatic** [comment]
I just added my first draft - let's see how you like it and then we can define how to make it look for the firs release.
